2.0.8.1.4

diff --git a/Modulos/conexao b/Modulos/conexao
--- a/Modulos/conexao
+++ b/Modulos/conexao
@@ -64,150 +64,6 @@ SCOLOR='\033[0m'
 	fun_wbsecurity () {
 	rm -rf /usr/bin/menusec && curl -s -L -o /usr/bin/menusec https://github.com/xzlordzx/sshpro/raw/main/menusec && chmod +x /usr/bin/menusec
 	}
-	inst_sqd() {
-		if netstat -nltp | grep 'squid' 1>/dev/null 2>/dev/null; then
-			echo -e "\E[41;1;37m            REMOVER SQUID PROXY              \E[0m"
-			echo ""
-			echo -ne "\033[1;32mREALMENTE DESEJA REMOVER O SQUID \033[1;31m? \033[1;33m[s/n]:\033[1;37m "
-			read resp
-			[[ "$resp" = 's' ]] && {
-				echo -e "\n\033[1;32mREMOVENDO O SQUID PROXY !\033[0m"
-				echo ""
-				rem_sqd() {
-					[[ -d "/etc/squid" ]] && {
-						apt-get remove squid -y >/dev/null 2>&1
-						apt-get purge squid -y >/dev/null 2>&1
-						rm -rf /etc/squid >/dev/null 2>&1
-					}
-					[[ -d "/etc/squid3" ]] && {
-						apt-get remove squid3 -y >/dev/null 2>&1
-						apt-get purge squid3 -y >/dev/null 2>&1
-						rm -rf /etc/squid3 >/dev/null 2>&1
-						apt autoremove -y >/dev/null 2>&1
-					}
-				}
-				fun_bar 'rem_sqd'
-				echo -e "\n\033[1;32mSQUID REMOVIDO COM SUCESSO !\033[0m"
-				sleep 2
-				clear
-				fun_conexao
-			} || {
-				echo -e "\n\033[1;31mRetornando...\033[0m"
-				sleep 2
-				clear
-				fun_conexao
-			}
-		else
-			clear
-			echo -e "\E[44;1;37m              INSTALADOR SQUID                \E[0m"
-			echo ""
-			IP=$(wget -qO- ipv4.icanhazip.com)
-			echo -ne "\033[1;32mPARA CONTINUAR CONFIRME SEU IP: \033[1;37m"
-			read -e -i $IP ipdovps
-			[[ -z "$ipdovps" ]] && {
-				echo -e "\n\033[1;31mIP invalido\033[1;32m"
-				echo ""
-				read -p "Digite seu IP: " IP
-			}
-			echo -e "\n\033[1;33mQUAIS PORTAS DESEJA ULTILIZAR NO SQUID \033[1;31m?"
-			echo -e "\n\033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mDEFINA AS PORTAS EM SEQUENCIA \033[1;33mEX: \033[1;37m80 8080"
-			echo ""
-			echo -ne "\033[1;32mINFORME AS PORTAS\033[1;37m: "
-			read portass
-			[[ -z "$portass" ]] && {
-				echo -e "\n\033[1;31mPorta invalida!"
-				sleep 3
-				fun_conexao
-			}
-			for porta in $(echo -e $portass); do
-				verif_ptrs $porta
-			done
-			[[ $(grep -wc '14' /etc/issue.net) != '0' ]] || [[ $(grep -wc '8' /etc/issue.net) != '0' ]] && {
-				echo -e "\n\033[1;32mINSTALANDO SQUID PROXY\033[0m\n"
-				fun_bar 'apt update -y' "apt install squid3 -y"
-			} || {
-				echo -e "\n\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mSQUID VERSAO 3.3.X\n\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mSQUID VERSAO 3.5.X\033[0m\n"
-				read -p "$(echo -e "\033[1;32mINFORME UMA OPÇÃO \033[1;37m: ")" -e -i 1 opc
-				[[ -z "$opc" ]] && {
-					echo -e "\n\033[1;31mOpcao invalida!"
-					sleep 2
-					fun_conexao
-				}
-				[[ "$opc" != '1' ]] && {
-					[[ "$opc" != '2' ]] && {
-						echo -e "\n\033[1;31mOpcao invalida !"
-						sleep 2
-						fun_conexao
-					}
-				}
-				echo -e "\n\033[1;32mINSTALANDO SQUID PROXY\033[0m\n"
-				fun_bar 'apt update -y' "instsqd $opc"
-			}
-			if [[ -d "/etc/squid/" ]]; then
-				var_sqd="/etc/squid/squid.conf"
-				var_pay="/etc/squid/payload.txt"
-			elif [[ -d "/etc/squid3/" ]]; then
-				var_sqd="/etc/squid3/squid.conf"
-				var_pay="/etc/squid3/payload.txt"
-			else
-				echo -e "\n\033[1;33m[\033[1;31mERRO\033[1;33m]\033[1;37m: \033[1;33mO SQUID PROXY CORROMPEU\033[0m"
-				sleep 2
-				fun_conexao
-			fi
-			cat <<-EOF >$var_pay
-				.whatsapp.net/
-				.facebook.net/
-				.twitter.com/
-				.speedtest.net/
-			EOF
-			cat <<-EOF >$var_sqd
-				acl url1 dstdomain -i 127.0.0.1
-				acl url2 dstdomain -i localhost
-				acl url3 dstdomain -i $ipdovps
-				acl url4 dstdomain -i /SSHPLUS?
-				acl payload url_regex -i "$var_pay"
-				acl all src 0.0.0.0/0
-
-				http_access allow url1
-				http_access allow url2
-				http_access allow url3
-				http_access allow url4
-				http_access allow payload
-				http_access deny all
-				 
-				#Portas
-			EOF
-			for Pts in $(echo -e $portass); do
-				echo -e "http_port $Pts" >>$var_sqd
-				[[ -f "/usr/sbin/ufw" ]] && ufw allow $Pts/tcp
-			done
-			cat <<-EOF >>$var_sqd
-				#Nome squid
-				visible_hostname SSHPLUS 
-				via off
-				forwarded_for off
-				pipeline_prefetch off
-			EOF
-			sqd_conf() {
-				[[ -d "/etc/squid/" ]] && {
-					service ssh restart
-					/etc/init.d/squid restart
-					service squid restart
-				}
-				[[ -d "/etc/squid3/" ]] && {
-					service ssh restart
-					/etc/init.d/squid3 restart
-					service squid3 restart
-				}
-			}
-			echo -e "\n\033[1;32mCONFIGURANDO SQUID PROXY\033[0m"
-			echo ""
-			fun_bar 'sqd_conf'
-			echo -e "\n\033[1;32mSQUID INSTALADO COM SUCESSO!\033[0m"
-			sleep 2.5s
-			fun_conexao
-		fi
-	}
 	addpt_sqd() {
 		echo -e "\E[44;1;37m         ADICIONAR PORTA AO SQUID         \E[0m"
 		echo -e "\n\033[1;33mPORTAS EM USO: \033[1;32m$sqdp\n"
@@ -1545,75 +1401,6 @@ exit 0' >$RCLOCAL
 		sleep 3
 		fun_openvpn
 	}
-	fun_socksssh() {
-	    clear
-		echo -e "\E[44;1;37m               🚀 PROXY SOCKS 🚀                 \E[0m"
-        echo -e "\033[0;36m╔═════════════════════•⊱✦⊰•═════════════════════╗\033[0m"
-		echo -e "   \033[1;31m[\033[1;36m01\033[1;31m] \033[1;37m• \033[1;37mATIVAR/DESATIVAR \033[0m"
-		echo -e "   \033[1;31m[\033[1;36m02\033[1;31m] \033[1;37m• \033[1;37mABRIR PORTA\033[0m"
-		echo -e "   \033[1;31m[\033[1;36m00\033[1;31m] \033[1;37m• \033[1;37mVOLTAR\033[0m"
-		echo -e "\033[0;36m╚═════════════════════•⊱✦⊰•═════════════════════╝\033[0m"
-		echo -ne "   \033[1;31m➤ \033[1;32mOPÇÃO\033[1;33m\033[1;31m\033[1;37m: ";
-		read option
-		case $option in
-		1 | 01)
-		 
-		;;
-		2 | 02)
-		if ps x | grep -w antcrashvpn.sh | grep -v grep 1>/dev/null 2>/dev/null; then
-				sockspt=$(netstat -nplt | grep 'python' | awk {'print $4'} | cut -d: -f2 | xargs)
-				clear
-				echo -e "\E[44;1;37m            PROXY SOCKS             \E[0m"
-				echo ""
-				echo -e "\033[1;33mPORTAS EM USO: \033[1;32m$sockspt"
-				echo ""
-				echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR \033[1;33m?\033[1;37m: "
-				read porta
-				[[ -z "$porta" ]] && {
-					echo ""
-					echo -e "\033[1;31mPorta invalida!"
-					sleep 2
-					clear
-					fun_socksssh
-				}
-				verif_ptrs $porta
-				echo ""
-				echo -e "\033[1;32mINICIANDO O PROXY SOCKS NA PORTA \033[1;31m$porta\033[1;33m"
-				echo ""
-				abrirptsks() {
-					sleep 1
-					screen -dmS proxy1 antcrashvpn.sh "$porta"
-					[[ $(grep -wc "antcrashvpn.sh" /etc/autostart) = '0' ]] && {
-						echo -e "netstat -tlpn | grep -w $porta > /dev/null || screen -dmS proxy1 antcrashvpn.sh $porta" >>/etc/autostart
-					} || {
-						sed -i '/antcrashvpn.sh/d' /etc/autostart
-						echo -e "netstat -tlpn | grep -w $porta > /dev/null || screen -dmS proxy1 antcrashvpn.sh $porta" >>/etc/autostart
-					}
-					sleep 1
-				}
-				fun_bar 'abrirptsks'
-				echo ""
-				echo -e "\033[1;32mPROXY SOCKS ATIVADO COM SUCESSO\033[1;33m"
-				sleep 2
-				fun_conexao
-			else
-				clear
-				echo -e "\033[1;31mFUNCAO INDISPONIVEL\n\n\033[1;33mATIVE O SOCKS PRIMEIRO !\033[1;33m"
-				sleep 2
-				fun_socksssh
-			fi
-			;;
-		0 | 00)
-		clear
-		fun_conexao
-		;;
-		*)
-		echo -e "\033[1;31mOpcao invalida !\033[0m"
-		sleep 2
-		fun_socksssh
-	    ;;
-		esac
-	}
 	fun_openssh() {
 		clear
 		echo -e "\E[44;1;37m            OPENSSH            \E[0m"
@@ -1899,7 +1686,148 @@ echo -ne "  \033[1;31m➤ \033[1;32mOPÇÃO\033[1;33m\033[1;31m\033[1;37m: ";
 			;;
 			3 | 03)
 			clear
-			fun_squid
+			if netstat -nltp | grep 'squid' 1>/dev/null 2>/dev/null; then
+			echo -e "\E[41;1;37m            REMOVER SQUID PROXY              \E[0m"
+			echo ""
+			echo -ne "\033[1;32mREALMENTE DESEJA REMOVER O SQUID \033[1;31m? \033[1;33m[s/n]:\033[1;37m "
+			read resp
+			[[ "$resp" = 's' ]] && {
+				echo -e "\n\033[1;32mREMOVENDO O SQUID PROXY !\033[0m"
+				echo ""
+				rem_sqd() {
+					[[ -d "/etc/squid" ]] && {
+						apt-get remove squid -y >/dev/null 2>&1
+						apt-get purge squid -y >/dev/null 2>&1
+						rm -rf /etc/squid >/dev/null 2>&1
+					}
+					[[ -d "/etc/squid3" ]] && {
+						apt-get remove squid3 -y >/dev/null 2>&1
+						apt-get purge squid3 -y >/dev/null 2>&1
+						rm -rf /etc/squid3 >/dev/null 2>&1
+						apt autoremove -y >/dev/null 2>&1
+					}
+				}
+				fun_bar 'rem_sqd'
+				echo -e "\n\033[1;32mSQUID REMOVIDO COM SUCESSO !\033[0m"
+				sleep 2
+				clear
+				fun_conexao
+			} || {
+				echo -e "\n\033[1;31mRetornando...\033[0m"
+				sleep 2
+				clear
+				fun_conexao
+			}
+		else
+			clear
+			echo -e "\E[44;1;37m              INSTALADOR SQUID                \E[0m"
+			echo ""
+			IP=$(wget -qO- ipv4.icanhazip.com)
+			echo -ne "\033[1;32mPARA CONTINUAR CONFIRME SEU IP: \033[1;37m"
+			read -e -i $IP ipdovps
+			[[ -z "$ipdovps" ]] && {
+				echo -e "\n\033[1;31mIP invalido\033[1;32m"
+				echo ""
+				read -p "Digite seu IP: " IP
+			}
+			echo -e "\n\033[1;33mQUAIS PORTAS DESEJA ULTILIZAR NO SQUID \033[1;31m?"
+			echo -e "\n\033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mDEFINA AS PORTAS EM SEQUENCIA \033[1;33mEX: \033[1;37m80 8080"
+			echo ""
+			echo -ne "\033[1;32mINFORME AS PORTAS\033[1;37m: "
+			read portass
+			[[ -z "$portass" ]] && {
+				echo -e "\n\033[1;31mPorta invalida!"
+				sleep 3
+				fun_conexao
+			}
+			for porta in $(echo -e $portass); do
+				verif_ptrs $porta
+			done
+			[[ $(grep -wc '14' /etc/issue.net) != '0' ]] || [[ $(grep -wc '8' /etc/issue.net) != '0' ]] && {
+				echo -e "\n\033[1;32mINSTALANDO SQUID PROXY\033[0m\n"
+				fun_bar 'apt update -y' "apt install squid3 -y"
+			} || {
+				echo -e "\n\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mSQUID VERSAO 3.3.X\n\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mSQUID VERSAO 3.5.X\033[0m\n"
+				read -p "$(echo -e "\033[1;32mINFORME UMA OPÇÃO \033[1;37m: ")" -e -i 1 opc
+				[[ -z "$opc" ]] && {
+					echo -e "\n\033[1;31mOpcao invalida!"
+					sleep 2
+					fun_conexao
+				}
+				[[ "$opc" != '1' ]] && {
+					[[ "$opc" != '2' ]] && {
+						echo -e "\n\033[1;31mOpcao invalida !"
+						sleep 2
+						fun_conexao
+					}
+				}
+				echo -e "\n\033[1;32mINSTALANDO SQUID PROXY\033[0m\n"
+				fun_bar 'apt update -y' "instsqd $opc"
+			}
+			if [[ -d "/etc/squid/" ]]; then
+				var_sqd="/etc/squid/squid.conf"
+				var_pay="/etc/squid/payload.txt"
+			elif [[ -d "/etc/squid3/" ]]; then
+				var_sqd="/etc/squid3/squid.conf"
+				var_pay="/etc/squid3/payload.txt"
+			else
+				echo -e "\n\033[1;33m[\033[1;31mERRO\033[1;33m]\033[1;37m: \033[1;33mO SQUID PROXY CORROMPEU\033[0m"
+				sleep 2
+				fun_conexao
+			fi
+			cat <<-EOF >$var_pay
+				.whatsapp.net/
+				.facebook.net/
+				.twitter.com/
+				.speedtest.net/
+			EOF
+			cat <<-EOF >$var_sqd
+				acl url1 dstdomain -i 127.0.0.1
+				acl url2 dstdomain -i localhost
+				acl url3 dstdomain -i $ipdovps
+				acl url4 dstdomain -i /SSHPLUS?
+				acl payload url_regex -i "$var_pay"
+				acl all src 0.0.0.0/0
+
+				http_access allow url1
+				http_access allow url2
+				http_access allow url3
+				http_access allow url4
+				http_access allow payload
+				http_access deny all
+				 
+				#Portas
+			EOF
+			for Pts in $(echo -e $portass); do
+				echo -e "http_port $Pts" >>$var_sqd
+				[[ -f "/usr/sbin/ufw" ]] && ufw allow $Pts/tcp
+			done
+			cat <<-EOF >>$var_sqd
+				#Nome squid
+				visible_hostname SSHPLUS 
+				via off
+				forwarded_for off
+				pipeline_prefetch off
+			EOF
+			sqd_conf() {
+				[[ -d "/etc/squid/" ]] && {
+					service ssh restart
+					/etc/init.d/squid restart
+					service squid restart
+				}
+				[[ -d "/etc/squid3/" ]] && {
+					service ssh restart
+					/etc/init.d/squid3 restart
+					service squid3 restart
+				}
+			}
+			echo -e "\n\033[1;32mCONFIGURANDO SQUID PROXY\033[0m"
+			echo ""
+			fun_bar 'sqd_conf'
+			echo -e "\n\033[1;32mSQUID INSTALADO COM SUCESSO!\033[0m"
+			sleep 2.5s
+			fun_conexao
+		fi
 			;;
 			4 | 04)
 			clear
