2.0.8.1.3

diff --git a/Modulos/conexao b/Modulos/conexao
--- a/Modulos/conexao
+++ b/Modulos/conexao
@@ -1557,68 +1557,7 @@ exit 0' >$RCLOCAL
 		read option
 		case $option in
 		1 | 01)
-		 if ps x | grep -w antcrashvpn.sh | grep -v grep 1>/dev/null 2>/dev/null; then
-				clear
-				echo -e "\E[41;1;37m             PROXY SOCKS              \E[0m"
-				echo ""
-				fun_socksoff() {
-					for pidproxy in $(screen -ls | grep ".proxy1" | awk {'print $1'}); do
-						screen -X -S "$pidproxy" kill
-					done
-					[[ $(grep -wc "antcrashvpn.sh" /etc/autostart) != '0' ]] && {
-						sed -i '/antcrashvpn.sh/d' /etc/autostart
-					}
-					sleep 1
-					screen -wipe >/dev/null
-				}
-				fun_socksofff() {
-				sudo systemctl disable --now socks.service && sudo systemctl stop socks.service && sudo systemctl daemon-reload
-				}
-				echo -e "\033[1;32mDESATIVANDO O PROXY SOCKS\033[1;33m"
-				echo ""
-				fun_socksoff
-				fun_socksofff
-				echo ""
-				echo -e "\033[1;32mPROXY SOCKS DESATIVADO COM SUCESSO!\033[1;33m"
-				sleep 3
-				fun_conexao
-		 else
-				clear
-				echo -e "\E[44;1;37m             PROXY SOCKS              \E[0m"
-				echo ""
-				echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR:\033[1;37m "
-				read porta
-				[[ -z "$porta" ]] && {
-					echo ""
-					echo -e "\033[1;31mPorta invalida!"
-					sleep 3
-					clear
-					fun_conexao
-				}
-				verif_ptrs $porta
-				fun_inisocks() {
-					sleep 1
-					screen -dmS proxy1 antcrashvpn.sh "$porta"
-					[[ $(grep -wc "antcrashvpn.sh" /etc/autostart) = '0' ]] && {
-						echo -e "netstat -tlpn | grep -w $porta > /dev/null || screen -dmS proxy1 antcrashvpn.sh $porta" >>/etc/autostart
-					} || {
-						sed -i '/antcrashvpn.sh/d' /etc/autostart
-						echo -e "netstat -tlpn | grep -w $porta > /dev/null || screen -dmS proxy1 antcrashvpn.sh $porta" >>/etc/autostart
-					}
-				}
-				fun_socksinit() {
-				sudo systemctl enable socks.service && sudo systemctl start socks.service
-				}
-				echo ""
-				echo -e "\033[1;32mINICIANDO O PROXY SOCKS\033[1;33m"
-				echo ""
-				fun_bar 'fun_inisocks'
-				fun_socksinit
-				echo ""
-				echo -e "\033[1;32mSOCKS ATIVADO COM SUCESSO\033[1;33m"
-				sleep 3
-				fun_conexao
-			fi
+		 
 		;;
 		2 | 02)
 		if ps x | grep -w antcrashvpn.sh | grep -v grep 1>/dev/null 2>/dev/null; then
@@ -1673,84 +1612,6 @@ exit 0' >$RCLOCAL
 		sleep 2
 		fun_socksssh
 	    ;;
-		esac
-	}
-	fun_websockett() {
-	    clear
-		echo -e "\E[44;1;37m                🚀 WEBSOCKET 🚀                  \E[0m"
-        echo -e "\033[0;36m╔═════════════════════•⊱✦⊰•═════════════════════╗\033[0m"
-		echo -e "   \033[1;31m[\033[1;36m01\033[1;31m] \033[1;37m• \033[1;37mATIVAR/DESATIVAR\033[0m"
-		echo -e "   \033[1;31m[\033[1;36m00\033[1;31m] \033[1;37m• \033[1;37mVOLTAR\033[0m"
-		echo -e "\033[0;36m╚═════════════════════•⊱✦⊰•═════════════════════╝\033[0m"
-		echo -ne "   \033[1;31m➤ \033[1;32mOPÇÃO\033[1;33m\033[1;31m\033[1;37m: ";
-		read option
-		case $option in
-		1 | 01)
-		clear
-		if ps x | grep -w antcrashvpn2.sh | grep -v grep 1>/dev/null 2>/dev/null; then
-		clear
-		echo -e "\E[41;1;37m             WEBSOCKET              \E[0m"
-		echo ""
-		fun_wssocksoff() {
-		for pidproxy in $(screen -ls | grep ".proxy2" | awk {'print $1'}); do
-		screen -r -S "$pidproxy" -X quit
-		done
-		[[ $(grep -wc "antcrashvpn2.sh" /etc/autostart) != '0' ]] && {
-						sed -i '/antcrashvpn2.sh/d' /etc/autostart
-					}
-					sleep 1
-					screen -wipe >/dev/null
-				}
-				echo -e "\033[1;32mDESATIVANDO O WEBSOCKET\033[1;33m"
-				echo ""
-				fun_bar 'fun_wssocksoff'
-				echo ""
-				echo -e "\033[1;32mWEBSOCKET DESATIVADO COM SUCESSO!\033[1;33m"
-				sleep 3
-				fun_conexao
-			else
-				clear
-				echo -e "\E[44;1;37m             WEBSOCKET              \E[0m"
-				echo ""
-				echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR \033[1;33m?\033[1;37m: "
-				read porta
-				[[ -z "$porta" ]] && {
-					echo ""
-					echo -e "\033[1;31mPorta invalida!"
-					sleep 3
-					clear
-					fun_conexao
-				}
-				verif_ptrs $porta
-				fun_iniwssocks() {
-					sleep 1
-					screen -dmS proxy2 antcrashvpn2.sh "$porta"
-					[[ $(grep -wc "antcrashvpn2.sh" /etc/autostart) = '0' ]] && {
-						echo -e "netstat -tlpn | grep -w $porta > /dev/null || screen -dmS proxy2 antcrashvpn2.sh $porta" >>/etc/autostart
-					} || {
-						sed -i '/antcrashvpn2.sh/d' /etc/autostart
-						echo -e "netstat -tlpn | grep -w $porta > /dev/null || screen -dmS proxy2 antcrashvpn2.sh $porta" >>/etc/autostart
-					}
-				}
-				echo ""
-				echo -e "\033[1;32m  INICIANDO O WEBSOCKET\033[1;33m"
-				echo ""
-				fun_bar 'fun_iniwssocks'
-				echo ""
-				echo -e "\033[1;32  WEBSOCKET ATIVADO COM SUCESSO\033[1;33m"
-				sleep 3
-				fun_conexao
-			fi
-		;;
-		0 | 00)
-		clear
-		fun_conexao
-		;;
-		*)
-		echo -e "\033[1;31mOpcao invalida !\033[0m"
-		sleep 2
-		fun_websockett
-		;;
 		esac
 	}
 	fun_openssh() {
@@ -1973,7 +1834,68 @@ echo -ne "  \033[1;31m➤ \033[1;32mOPÇÃO\033[1;33m\033[1;31m\033[1;37m: ";
 			;;
 			2 | 02)
 			clear
-		    fun_socksssh
+		    if ps x | grep -w antcrashvpn.sh | grep -v grep 1>/dev/null 2>/dev/null; then
+				clear
+				echo -e "\E[41;1;37m             PROXY SOCKS              \E[0m"
+				echo ""
+				fun_socksoff() {
+					for pidproxy in $(screen -ls | grep ".proxy1" | awk {'print $1'}); do
+						screen -X -S "$pidproxy" kill
+					done
+					[[ $(grep -wc "antcrashvpn.sh" /etc/autostart) != '0' ]] && {
+						sed -i '/antcrashvpn.sh/d' /etc/autostart
+					}
+					sleep 1
+					screen -wipe >/dev/null
+				}
+				fun_socksofff() {
+				sudo systemctl disable --now socks.service && sudo systemctl stop socks.service && sudo systemctl daemon-reload
+				}
+				echo -e "\033[1;32mDESATIVANDO O PROXY SOCKS\033[1;33m"
+				echo ""
+				fun_socksoff
+				fun_socksofff
+				echo ""
+				echo -e "\033[1;32mPROXY SOCKS DESATIVADO COM SUCESSO!\033[1;33m"
+				sleep 3
+				fun_conexao
+		 else
+				clear
+				echo -e "\E[44;1;37m             PROXY SOCKS              \E[0m"
+				echo ""
+				echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR:\033[1;37m "
+				read porta
+				[[ -z "$porta" ]] && {
+					echo ""
+					echo -e "\033[1;31mPorta invalida!"
+					sleep 3
+					clear
+					fun_conexao
+				}
+				verif_ptrs $porta
+				fun_inisocks() {
+					sleep 1
+					screen -dmS proxy1 antcrashvpn.sh "$porta"
+					[[ $(grep -wc "antcrashvpn.sh" /etc/autostart) = '0' ]] && {
+						echo -e "netstat -tlpn | grep -w $porta > /dev/null || screen -dmS proxy1 antcrashvpn.sh $porta" >>/etc/autostart
+					} || {
+						sed -i '/antcrashvpn.sh/d' /etc/autostart
+						echo -e "netstat -tlpn | grep -w $porta > /dev/null || screen -dmS proxy1 antcrashvpn.sh $porta" >>/etc/autostart
+					}
+				}
+				fun_socksinit() {
+				sudo systemctl enable socks.service && sudo systemctl start socks.service
+				}
+				echo ""
+				echo -e "\033[1;32mINICIANDO O PROXY SOCKS\033[1;33m"
+				echo ""
+				fun_bar 'fun_inisocks'
+				fun_socksinit
+				echo ""
+				echo -e "\033[1;32mSOCKS ATIVADO COM SUCESSO\033[1;33m"
+				sleep 3
+				fun_conexao
+			fi
 			;;
 			3 | 03)
 			clear
@@ -1981,7 +1903,60 @@ echo -ne "  \033[1;31m➤ \033[1;32mOPÇÃO\033[1;33m\033[1;31m\033[1;37m: ";
 			;;
 			4 | 04)
 			clear
-			fun_websockett
+			if ps x | grep -w antcrashvpn2.sh | grep -v grep 1>/dev/null 2>/dev/null; then
+		clear
+		echo -e "\E[41;1;37m             WEBSOCKET              \E[0m"
+		echo ""
+		fun_wssocksoff() {
+		for pidproxy in $(screen -ls | grep ".proxy2" | awk {'print $1'}); do
+		screen -r -S "$pidproxy" -X quit
+		done
+		[[ $(grep -wc "antcrashvpn2.sh" /etc/autostart) != '0' ]] && {
+						sed -i '/antcrashvpn2.sh/d' /etc/autostart
+					}
+					sleep 1
+					screen -wipe >/dev/null
+				}
+				echo -e "\033[1;32mDESATIVANDO O WEBSOCKET\033[1;33m"
+				echo ""
+				fun_bar 'fun_wssocksoff'
+				echo ""
+				echo -e "\033[1;32mWEBSOCKET DESATIVADO COM SUCESSO!\033[1;33m"
+				sleep 3
+				fun_conexao
+			else
+				clear
+				echo -e "\E[44;1;37m             WEBSOCKET              \E[0m"
+				echo ""
+				echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR \033[1;33m?\033[1;37m: "
+				read porta
+				[[ -z "$porta" ]] && {
+					echo ""
+					echo -e "\033[1;31mPorta invalida!"
+					sleep 3
+					clear
+					fun_conexao
+				}
+				verif_ptrs $porta
+				fun_iniwssocks() {
+					sleep 1
+					screen -dmS proxy2 antcrashvpn2.sh "$porta"
+					[[ $(grep -wc "antcrashvpn2.sh" /etc/autostart) = '0' ]] && {
+						echo -e "netstat -tlpn | grep -w $porta > /dev/null || screen -dmS proxy2 antcrashvpn2.sh $porta" >>/etc/autostart
+					} || {
+						sed -i '/antcrashvpn2.sh/d' /etc/autostart
+						echo -e "netstat -tlpn | grep -w $porta > /dev/null || screen -dmS proxy2 antcrashvpn2.sh $porta" >>/etc/autostart
+					}
+				}
+				echo ""
+				echo -e "\033[1;32m  INICIANDO O WEBSOCKET\033[1;33m"
+				echo ""
+				fun_bar 'fun_iniwssocks'
+				echo ""
+				echo -e "\033[1;32  WEBSOCKET ATIVADO COM SUCESSO\033[1;33m"
+				sleep 3
+				fun_conexao
+			fi
 			;;
 			5 | 05)
 			clear
