2.6.2

diff --git a/Modulos/conexao b/Modulos/conexao
--- a/Modulos/conexao
+++ b/Modulos/conexao
@@ -1540,6 +1540,157 @@ exit 0' >$RCLOCAL
 			}
 		}
 	}
+	inst_paineldt () {
+    rm -rf /root/dtmod.sh && wget https://script.cvpn.top/dtmod.sh && chmod 777 dtmod.sh
+}
+    fazerbackup() {
+  clear
+  echo "Fazendo backcup..."
+  rm -rf /root/painelbackup.zip
+  cd /root/PainelDT
+  #mkdir painelbackup > /dev/null
+  cp prisma/database.db painelbackup
+  cp .env painelbackup
+  zip -r painelbackup.zip painelbackup
+  mv painelbackup.zip /root
+  echo
+  echo "painelbackup.zip salvo em /root"
+}
+painelapp_bkp (){
+clear
+[[ $(netstat -nplt | grep -wc 'node') != '0' ]] && dt_sks="\033[1;32m⬤ " || dt_sks="\033[1;31m⬤ "
+echo -e "\E[44;1;37m                  ⚡ PAINEL DT ⚡                  \E[0m"
+echo -e "\033[0;36m╔══════════════════════•⊱✦⊰•══════════════════════╗\033[0m"
+echo -e "\033[0;31m    \033[1;37m FUNCIONA APENAS NO UBUNTU 20\033[0;31m"
+echo -e "\033[0;36m° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° °\033[0m"
+echo -e "\033[0;31m   [\033[1;36m01\033[0;31m] \033[1;37m• \033[1;37mFAZER BACKUP\033[0;31m
+\033[0;31m   [\033[1;36m02\033[0;31m] \033[1;37m• \033[1;37mRESTAURAR\033[0;31m
+\033[0;31m   [\033[1;36m03\033[0;31m] \033[1;37m• \033[1;37mATIVAR BACKUP AUTOMATICO\033[0;31m
+\033[0;31m   [\033[1;36m00\033[0;31m] \033[1;37m• \033[1;37mVOLTAR  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
+echo -e "\033[0;36m╚══════════════════════•⊱✦⊰•══════════════════════╝\033[0m"
+echo -ne "   \033[1;31m➤ \033[1;32mOPÇÃO\033[1;33m\033[1;31m\033[1;37m: "; read x
+case "$x" in
+   1 | 01)
+   clear
+   fun_bar 'fazerbackup'
+   echo ""
+   echo -e "\033[1;32m  BACKUP FEITO COM SUCESSO!\033[1;33m"
+   echo -e "\033[1;32mBACKUP: painelbackup.zip SALVO EM: /root\033[1;33m"
+   sleep 2
+   painelapp
+   ;;
+   2 | 02)
+   clear
+    [[ ! -e /root/painelbackup.zip ]] && {
+    echo ""
+	echo -e "\033[1;32mARQUIVO: painelbackup.zip NÃO ENCONTRADO EM: /root\033[1;33m"
+    sleep 4
+    painelapp_bkp
+  }
+  read -p "DESEJA RESTAURAR O BACKUP? (s/n) " rapi
+  [[ $rapi = @(s|S) ]] && {
+    echo -e "\033[1;32mRESTAURANDO...\033[1;33m"
+    cd /root/PainelDT
+    rm prisma/database.db
+    rm .env
+    cd /root
+    unzip painelbackup.zip
+    cd painelbackup
+    mv database.db ../PainelDT/prisma
+    mv .env ../PainelDT
+    cd /root
+    rm -r painelbackup
+    pon
+    echo
+    echo -e "\033[1;32mBACKUP RESTAURADO COM SUCESSO!\033[1;33m"
+	sleep 4
+  }
+  [[ $rapi = @(n|N) ]] && {
+    painelapp_bkp
+	}
+    painelapp_bkp
+   ;;
+   3 | 03)
+   clear
+   read -p "ATIVAR BACKUP AUTOMATICO? (s/n) " atb
+   [[ $atb = @(s|S) ]] && {
+    echo -e "\033[1;32mATIVANDO..\033[1;33m"
+    backmod
+    echo
+	echo -e "\033[1;32mBACKUP SERÁ FEITO A CADA 5 HORAS!\033[1;33m"
+	sleep 4
+  }
+   painelapp_bkp
+   ;;
+   0 | 00)
+   clear
+   painelapp
+   ;;
+   *)
+   echo -e "\n\033[1;31mOpcao invalida !\033[0m"
+   sleep 2
+   painelapp_bkp
+   ;;
+esac
+}
+painelapp (){
+clear
+[[ $(netstat -nplt | grep -wc 'node') != '0' ]] && dt_sks="\033[1;32m⬤ " || dt_sks="\033[1;31m⬤ "
+echo -e "\E[44;1;37m                  ⚡ PAINEL DT ⚡                  \E[0m"
+echo -e "\033[0;36m╔══════════════════════•⊱✦⊰•══════════════════════╗\033[0m"
+echo -e "\033[0;31m    \033[1;37m FUNCIONA APENAS NO UBUNTU 20\033[0;31m"
+echo -e "\033[0;36m° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° °\033[0m"
+echo -e "\033[0;31m   [\033[1;36m01\033[0;31m] \033[1;37m• \033[1;37mINSTALAR/REMOVER\033[0;31m
+\033[0;31m   [\033[1;36m02\033[0;31m] \033[1;37m• \033[1;37mATIVAR $dt_sks\033[0;31m
+\033[0;31m   [\033[1;36m03\033[0;31m] \033[1;37m• \033[1;37mDESATIVAR $dt_sks\033[0;31m
+\033[0;31m   [\033[1;36m04\033[0;31m] \033[1;37m• \033[1;37mGERENCIAR BACKUP\033[0;31m
+\033[0;31m   [\033[1;36m00\033[0;31m] \033[1;37m• \033[1;37mVOLTAR  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
+echo -e "\033[0;36m╚══════════════════════•⊱✦⊰•══════════════════════╝\033[0m"
+echo -ne "   \033[1;31m➤ \033[1;32mOPÇÃO\033[1;33m\033[1;31m\033[1;37m: "; read x
+case "$x" in
+   1 | 01)
+   clear
+   fun_bar 'inst_paineldt'
+   ./dtmod.sh
+   painelapp
+   ;;
+   2 | 02)
+    clear
+	echo -e "\033[1;32mINICIANDO O PAINEL\033[1;33m"
+	echo ""
+	pon
+	sudo systemctl enable paineldt.service && sudo systemctl start paineldt.service
+	echo ""
+	echo -e "\033[1;32mPAINEL ATIVADO COM SUCESSO\033[1;33m"
+	sleep 3
+    painelapp
+   ;;
+   3 | 03)
+    clear
+	echo -e "\033[1;32mDESATIVANDO O PAINEL\033[1;33m"
+	echo ""
+	poff
+	sudo systemctl disable --now paineldt.service && sudo systemctl stop paineldt.service && sudo systemctl daemon-reload
+	echo ""
+	echo -e "\033[1;32mPAINEL DESATIVADO COM SUCESSO!\033[1;33m"
+	sleep 3
+	painelapp
+    ;;
+   4 | 04)
+   clear
+   painelapp_bkp
+   ;;
+   0 | 00)
+   clear
+   menu
+   ;;
+   *)
+   echo -e "\n\033[1;31mOpcao invalida !\033[0m"
+   sleep 2
+   menu
+   ;;
+esac
+}
 	x="ok"
 	fun_conexao() {
 		while true $x != "ok"; do
@@ -1551,109 +1702,115 @@ echo -e "\E[44;1;37m                     🚀 CONEXÕES 🚀                    
 echo -e "\033[0;36m╔════════════════════════•⊱✦⊰•════════════════════════╗\033[0m"
 echo -e "   \033[1;33mOPENSSH: \033[1;32mPORTA: \033[1;37m$(grep 'Port' /etc/ssh/sshd_config | cut -d' ' -f2 | grep -v 'no' | xargs)" && sks01="\033[1;32m⬤ "          
 			[[ "$(netstat -tlpn | grep 'sslh' | wc -l)" != '0' ]] && {
-				echo -e "   \033[1;33mSSLH: \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'sslh' | awk {'print $4'} | cut -d: -f2 | xargs)"
+				echo -e "   \033[1;33mSSLH: \033[1;32m$(netstat -nplt | grep 'sslh' | awk {'print $4'} | cut -d: -f2 | xargs)"
 				sks09="\033[1;32m⬤ "
 			} || {
 				sks09="\033[1;31m⬤ "
 			}
 			[[ "$(netstat -tlpn | grep 'openvpn' | wc -l)" != '0' ]] && {
-				echo -e "   \033[1;33mOPENVPN: \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'openvpn' | awk {'print $4'} | cut -d: -f2 | xargs)"
+				echo -e "   \033[1;33mOPENVPN: \033[1;32m$(netstat -nplt | grep 'openvpn' | awk {'print $4'} | cut -d: -f2 | xargs)"
 				sks06="\033[1;32m⬤ "
 			} || {
 				sks06="\033[1;31m⬤ "
 			}
 			[[ "$(netstat -tlpn | grep 'python' | wc -l)" != '0' ]] && {
-				echo -e "   \033[1;33mSOCKS/WEBSOCKET: \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'python' | awk {'print $4'} | cut -d: -f2 | xargs)"
+				echo -e "   \033[1;33mSOCKS/WEBSOCKET: \033[1;32m$(netstat -nplt | grep 'python' | awk {'print $4'} | cut -d: -f2 | xargs)"
 				sks400="\033[1;32m⬤ "
 			} || {
 				sks400="\033[1;31m⬤ "
 			}
 			[[ -e "/etc/stunnel/stunnel.conf" ]] && {
-				echo -e "   \033[1;33mSSL TUNNEL: \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'stunnel' | awk {'print $4'} | cut -d: -f2 | xargs)"
+				echo -e "   \033[1;33mSSL TUNNEL: \033[1;32m$(netstat -nplt | grep 'stunnel' | awk {'print $4'} | cut -d: -f2 | xargs)"
 				sks07="\033[1;32m⬤ "
 			} || {
 				sks07="\033[1;31m⬤ "
 			}
 			[[ "$(netstat -tlpn | grep 'dropbear' | wc -l)" != '0' ]] && {
-				echo -e "   \033[1;33mDROPBEAR: \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'dropbear' | awk -F ":" {'print $4'} | xargs)"
+				echo -e "   \033[1;33mDROPBEAR: \033[1;32m$(netstat -nplt | grep 'dropbear' | awk -F ":" {'print $4'} | xargs)"
 				sks05="\033[1;32m⬤ "
 			} || {
 				sks05="\033[1;31m⬤ "
 			}
 			[[ "$(netstat -tlpn | grep 'squid' | wc -l)" != '0' ]] && {
-				echo -e "   \033[1;33mSQUID: \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'squid' | awk -F ":" {'print $4'} | xargs)"
+				echo -e "   \033[1;33mSQUID: \033[1;32m$(netstat -nplt | grep 'squid' | awk -F ":" {'print $4'} | xargs)"
 				sks03="\033[1;32m⬤ "
 			} || {
 				sks03="\033[1;31m⬤ "
 			}
 			[[ "$(netstat -tlpn | grep 'WebSocket' | wc -l)" != '0' ]] && {
-				echo -e "   \033[1;33mSECURITY: \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'WebSocket' | awk -F ":" {'print $4'} | xargs)"
+				echo -e "   \033[1;33mSECURITY: \033[1;32m$(netstat -nplt | grep 'WebSocket' | awk -F ":" {'print $4'} | xargs)"
 				sks10="\033[1;32m⬤ "
 			} || {
 				sks10="\033[1;31m⬤ "
 			}
             [[ $(netstat -nplt | grep -wc 'v2ray') != '0' ]] && {
 			sks08="\033[1;32m⬤ "
-			echo -e "   \033[1;33mV2RAY: \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'v2ray' | awk {'print $4'} | cut -d: -f2 | xargs)"
+			echo -e "   \033[1;33mV2RAY: \033[1;32m$(netstat -nplt | grep 'v2ray' | awk {'print $4'} | cut -d: -f2 | xargs)"
 	    	} || {
 			sks08="\033[1;31m⬤ "
 		    }
             [[ $(netstat -nplt | grep -wc 'proxy') != '0' ]] && {
 			sks11="\033[1;32m⬤ "
-			echo -e "   \033[1;33mPROXY-PRO: \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'proxy' | awk {'print $4'} | cut -d: -f2 | xargs)"
+			echo -e "   \033[1;33mPROXY-PRO: \033[1;32m$(netstat -nplt | grep 'proxy' | awk {'print $4'} | cut -d: -f2 | xargs)"
 		    } || {
 			sks11="\033[1;31m⬤ "
 		    }
+			[[ $(netstat -nplt | grep -wc 'node') != '0' ]] && {
+			dt_sks="\033[1;32m⬤ " 
+			echo -e "   \033[1;33mPAINEL DTUNNEL: \033[1;32m$(netstat -nplt | grep 'node' | awk {'print $4'} | cut -d: -f2 | xargs)"
+			} || {
+			dt_sks="\033[1;31m⬤ "
+			}
 echo -e "\033[0;36m° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° °\033[0m"
 echo -e "\033[0;31m  [\033[1;36m01\033[0;31m] \033[1;37m• \033[1;37mOPENSSH $sks01\033[0;31m                [\033[1;36m08\033[0;31m] \033[1;37m• \033[1;37mV2RAY $sks08\033[1;31m
 \033[0;31m  [\033[1;36m02\033[0;31m] \033[1;37m• \033[1;37mPROXY SOCKS $sks02\033[0;31m            [\033[1;36m09\033[0;31m] \033[1;37m• \033[1;37mSSLH $sks09\033[1;31m
 \033[0;31m  [\033[1;36m03\033[0;31m] \033[1;37m• \033[1;37mPROXY SQUID $sks03\033[0;31m            [\033[1;36m10\033[0;31m] \033[1;37m• \033[1;37mSECURITY $sks10\033[1;31m
 \033[0;31m  [\033[1;36m04\033[0;31m] \033[1;37m• \033[1;37mWEBSOCKET $sks04\033[0;31m              [\033[1;36m11\033[0;31m] \033[1;37m• \033[1;37mPROXY PRO $sks11\033[0;31m
-\033[0;31m  [\033[1;36m05\033[0;31m] \033[1;37m• \033[1;37mDROPBEAR $sks05\033[0;31m               [\033[1;36m00\033[0;31m] \033[1;37m• \033[1;37mVOLTAR  \033[1;32m<\033[1;33m<\033[1;31m<\033[0;31m
-\033[0;31m  [\033[1;36m06\033[0;31m] \033[1;37m• \033[1;37mOPENVPN $sks06\033[0;31m
+\033[0;31m  [\033[1;36m05\033[0;31m] \033[1;37m• \033[1;37mDROPBEAR $sks05\033[0;31m               [\033[1;36m12\033[0;31m] \033[1;37m• \033[1;37mPAINEL DTUNNEL $dt_sks\033[0;31m
+\033[0;31m  [\033[1;36m06\033[0;31m] \033[1;37m• \033[1;37mOPENVPN $sks06\033[0;31m                [\033[1;36m00\033[0;31m] \033[1;37m• \033[1;37mVOLTAR  \033[1;32m<\033[1;33m<\033[1;31m<\033[0;31m
 \033[0;31m  [\033[1;36m07\033[0;31m] \033[1;37m• \033[1;37mSSL TUNNEL $sks07\033[0m"
 echo -e "\033[0;36m╚════════════════════════•⊱✦⊰•════════════════════════╝\033[0m"
 echo -ne "  \033[1;31m➤ \033[1;32mOPÇÃO\033[1;33m\033[1;31m\033[1;37m: ";
-		read option
-		case $option in
-			1 | 01)
-			clear
-			fun_openssh
-			;;
-			2 | 02)
-			clear
-		    if ps x | grep -w antcrashvpn.sh | grep -v grep 1>/dev/null 2>/dev/null; then
-				clear
-				echo -e "\E[41;1;37m             PROXY SOCKS              \E[0m"
-				echo ""
-				fun_socksoff() {
-					for pidproxy in $(screen -ls | grep ".proxy1" | awk {'print $1'}); do
-						screen -X -S "$pidproxy" kill
-					done
-					[[ $(grep -wc "antcrashvpn.sh" /etc/autostart) != '0' ]] && {
-						sed -i '/antcrashvpn.sh/d' /etc/autostart
-					}
-					sleep 1
-					screen -wipe >/dev/null
-				}
-				fun_socksofff() {
-				sudo systemctl disable --now socks.service && sudo systemctl stop socks.service && sudo systemctl daemon-reload
-				}
-				echo -e "\033[1;32mDESATIVANDO O PROXY SOCKS\033[1;33m"
-				echo ""
-				fun_socksoff
-				fun_socksofff
-				echo ""
-				echo -e "\033[1;32mPROXY SOCKS DESATIVADO COM SUCESSO!\033[1;33m"
-				sleep 3
-				fun_conexao
-		 else
-				clear
-				echo -e "\E[44;1;37m             PROXY SOCKS              \E[0m"
-				echo ""
-				echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR:\033[1;37m "
-				read porta
-				[[ -z "$porta" ]] && {
+read option
+case $option in
+    1 | 01)
+	clear
+	fun_openssh
+    ;;
+	2 | 02)
+	clear
+	if ps x | grep -w antcrashvpn.sh | grep -v grep 1>/dev/null 2>/dev/null; then
+	clear
+	echo -e "\E[41;1;37m             PROXY SOCKS              \E[0m"
+	echo ""
+	fun_socksoff() {
+	for pidproxy in $(screen -ls | grep ".proxy1" | awk {'print $1'}); do
+		screen -X -S "$pidproxy" kill
+	done
+	[[ $(grep -wc "antcrashvpn.sh" /etc/autostart) != '0' ]] && {
+		sed -i '/antcrashvpn.sh/d' /etc/autostart
+	}
+	sleep 1
+	screen -wipe >/dev/null
+	}
+	fun_socksofff() {
+	    sudo systemctl disable --now socks.service && sudo systemctl stop socks.service && sudo systemctl daemon-reload
+	}
+	echo -e "\033[1;32mDESATIVANDO O PROXY SOCKS\033[1;33m"
+	echo ""
+	fun_socksoff
+	fun_socksofff
+	echo ""
+	echo -e "\033[1;32mPROXY SOCKS DESATIVADO COM SUCESSO!\033[1;33m"
+	sleep 3
+	fun_conexao
+		else
+	clear
+	echo -e "\E[44;1;37m             PROXY SOCKS              \E[0m"
+	echo ""
+	echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR:\033[1;37m "
+	read porta
+	[[ -z "$porta" ]] && {
 					echo ""
 					echo -e "\033[1;31mPorta invalida!"
 					sleep 3
@@ -1920,6 +2077,10 @@ echo -ne "  \033[1;31m➤ \033[1;32mOPÇÃO\033[1;33m\033[1;31m\033[1;37m: ";
 		    fun_bar 'fun_proxypro'
 		    clear
 	        proxypro
+			;;
+			12)
+			clear
+			painelapp
 			;;
 			0 | 00)
 			clear
