5.0.4

diff --git a/Modulos/conexao b/Modulos/conexao
--- a/Modulos/conexao
+++ b/Modulos/conexao
@@ -470,9 +470,9 @@ executar_comando() {
 				portssl='22'
 			elif [[ "$resposta" = '2' ]]; then
 				portssl='80'
-			elif [[ "resposta" = '3' ]]; {
-				echo -e "\033[1;32mREMOVENDO !\033[0m"
-				del_stunnel() {
+			[[ "$resposta" = '3' ]] && {
+				echo -e "\033[1;32mREMOVENDO O  SSL TUNNEL !\033[0m"
+				rem_ssl() {
 					service stunnel4 stop
 					apt-get remove stunnel4 -y
 					apt-get autoremove stunnel4 -y
@@ -483,11 +483,12 @@ executar_comando() {
 					rm -rf /etc/stunnel/key.key
 				}
 				echo ""
-				fun_bar 'del_stunnel'
+				fun_bar 'rem_ssl'
 				echo ""
-				echo -e "\033[1;32mREMOVIDO COM SUCESSO!\033[0m"
+				echo -e "\033[1;32mSSL TUNNEL REMOVIDO COM SUCESSO!\033[0m"
 				sleep 3
-				}				fun_conexao
+				fun_conexao
+			}
 			elif [[ "$resposta" = '0' ]]; then
 				echo -e "\033[1;31mRetornando...\033[0m"
 				sleep 3
@@ -1312,7 +1313,7 @@ exit 0' >$RCLOCAL
 		sleep 3
 		fun_openvpn
 	}
-	fun_openssh() {
+fun_openssh() {
 		clear
 		echo -e "\E[44;1;37m            OPENSSH            \E[0m"
 		echo -e "\033[0;36m╔════════════•⊱✦⊰•════════════╗\033[0m"
@@ -1323,34 +1324,34 @@ exit 0' >$RCLOCAL
 		echo -e "\033[0;36m╚════════════•⊱✦⊰•════════════╝\033[0m"
 		echo -ne "\033[1;31m➤ \033[1;32mOPÇÃO\033[1;33m\033[1;31m\033[1;37m: ";
 		read resp
-		if [[ "$resp" = '1' ]]; then
-			clear
-			echo -e "\E[44;1;37m         ADICIONAR PORTA AO SSH         \E[0m\n"
-			echo -ne "\033[1;32mQUAL PORTA DESEJA ADICIONAR \033[1;33m?\033[1;37m "
-			read pt
+	if [[ "$resp" = '1' ]]; then
+		clear
+		echo -e "\E[44;1;37m         ADICIONAR PORTA AO SSH         \E[0m\n"
+		echo -ne "\033[1;32mQUAL PORTA DESEJA ADICIONAR \033[1;33m?\033[1;37m "
+		read pt
 			[[ -z "$pt" ]] && {
 				echo -e "\n\033[1;31mPorta invalida!"
 				sleep 3
 				fun_conexao
 			}
-			verif_ptrs $pt
-			echo -e "\n\033[1;32mADICIONANDO PORTA AO SSH\033[0m"
-			echo ""
-			fun_addpssh() {
-				echo "Port $pt" >>/etc/ssh/sshd_config
-				service ssh restart
-			}
-			fun_bar 'fun_addpssh'
-			echo -e "\n\033[1;32mPORTA ADICIONADA COM SUCESSO\033[0m"
-			sleep 3
-			fun_conexao
-		elif [[ "$resp" = '2' ]]; then
-			clear
-			echo -e "\E[41;1;37m         REMOVER PORTA DO SSH         \E[0m"
-			echo -e "\n\033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mPORTA PADRAO \033[1;37m22 \033[1;33mCUIDADO !\033[0m"
-			echo -e "\n\033[1;33mPORTAS EM USO: \033[1;37m$(grep 'Port' /etc/ssh/sshd_config | cut -d' ' -f2 | grep -v 'no' | xargs)\n"
-			echo -ne "\033[1;32mQUAL PORTA DESEJA REMOVER \033[1;33m?\033[1;37m "
-			read pt
+		verif_ptrs $pt
+		echo -e "\n\033[1;32mADICIONANDO PORTA AO SSH\033[0m"
+		echo ""
+	    fun_addpssh() {
+		    echo "Port $pt" >>/etc/ssh/sshd_config
+		    service ssh restart
+		}
+		fun_bar 'fun_addpssh'
+		echo -e "\n\033[1;32mPORTA ADICIONADA COM SUCESSO\033[0m"
+		sleep 3
+		fun_conexao
+	elif [[ "$resp" = '2' ]]; then
+		clear
+		echo -e "\E[41;1;37m         REMOVER PORTA DO SSH         \E[0m"
+		echo -e "\n\033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mPORTA PADRAO \033[1;37m22 \033[1;33mCUIDADO !\033[0m"
+		echo -e "\n\033[1;33mPORTAS EM USO: \033[1;37m$(grep 'Port' /etc/ssh/sshd_config | cut -d' ' -f2 | grep -v 'no' | xargs)\n"
+		echo -ne "\033[1;32mQUAL PORTA DESEJA REMOVER \033[1;33m?\033[1;37m "
+		read pt
 			[[ -z "$pt" ]] && {
 				echo -e "\n\033[1;31mPorta invalida!"
 				sleep 2
@@ -1363,7 +1364,7 @@ exit 0' >$RCLOCAL
 					sed -i "/Port $pt/d" /etc/ssh/sshd_config
 					service ssh restart
 				}
-				fun_bar 'fun_delpssh'
+			    fun_bar 'fun_delpssh'
 				echo -e "\n\033[1;32mPORTA REMOVIDA COM SUCESSO\033[0m"
 				sleep 2
 				fun_conexao
@@ -1372,72 +1373,72 @@ exit 0' >$RCLOCAL
 				sleep 2
 				fun_conexao
 			}
-		elif [[ "$resp" = '3' ]]; then
-		    clear
-			echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mCORRIGINDO SSH \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
-            echo ""
-			fun_cossh () {
-	        echo 'MaxStartups 1500:10:1500' >> /etc/ssh/sshd_config && service ssh restart
-	        }
-		    fun_bar 'fun_cossh'
-			sleep 2
-			fun_conexao
-		elif [[ "$resp" = '0' ]]; then
-			clear
-		    echo ""
-		    echo -e "\033[1;33mVOLTANDO...\033[0m"
-		    sleep 1
-			fun_conexao
-		else
-			echo -e "\n\033[1;31mOpcao invalida!"
-			sleep 2
-			fun_conexao
-		fi
-	}
-	fun_socks() {
-	if ps x | grep -w proxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
+	elif [[ "$resp" = '3' ]]; then
 		clear
+		echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mCORRIGINDO SSH \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
+        echo ""
+		fun_cossh () {
+	        echo 'MaxStartups 1500:10:1500' >> /etc/ssh/sshd_config && service ssh restart
+	    }
+		fun_bar 'fun_cossh'
+		sleep 2
+		fun_conexao
+	elif [[ "$resp" = '0' ]]; then
+		clear
+		echo ""
+		echo -e "\033[1;33mVOLTANDO...\033[0m"
+		sleep 1
+		fun_conexao
+	else
+		echo -e "\n\033[1;31mOpcao invalida!"
+		sleep 2
+		fun_conexao
+	fi
+}
+fun_socks() {
+        clear
+	if ps x | grep -w antcrashvpn.sh | grep -v grep 1>/dev/null 2>/dev/null; then
 		echo -e "\E[41;1;37m             PROXY SOCKS              \E[0m"
 		echo ""
 	fun_socksoff() {
-			for pidproxy in $(screen -ls | grep ".proxy" | awk {'print $1'}); do
-			screen -r -S "$pidproxy" -X quit
-		done
-	[[ $(grep -wc "proxy.py" /etc/autostart) != '0' ]] && {
-		sed -i '/proxy.py/d' /etc/autostart
-	}
+	    for pidproxy in $(screen -ls | grep ".proxy" | awk {'print $1'}); do
+            screen -r -S "$pidproxy" -X quit
+        done
+	    [[ $(grep -wc "antcrashvpn.sh" /etc/autostart) != '0' ]] && {
+		    sed -i '/antcrashvpn.sh/d' /etc/autostart
+		}
 		sleep 1
 		screen -wipe >/dev/null
-		}
-		echo -e "\033[1;32mDESATIVANDO O PROXY SOCKS\033[1;33m"
+	}
+	    echo -e "\033[1;32mDESATIVANDO O PROXY SOCKS\033[1;33m"
 		echo ""
 		fun_bar 'fun_socksoff'
 		echo ""
 		echo -e "\033[1;32mPROXY SOCKS DESATIVADO COM SUCESSO!\033[1;33m"
 		sleep 3
-		fun_socks
+		menu_proxy
 	else
-		clear
+	    clear
 		echo -e "\E[44;1;37m             PROXY SOCKS              \E[0m"
 		echo ""
 		echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR \033[1;33m?\033[1;37m: "
 		read porta
-		 [[ -z "$porta" ]] && {
-		echo ""
-		echo -e "\033[1;31mPorta invalida!"
-	sleep 3
-		clear
-		menu_proxy
-	}
+		[[ -z "$porta" ]] && {
+			echo ""
+			echo -e "\033[1;31mPorta invalida!"
+			sleep 3
+			clear
+			fun_conexao
+		}
 		verif_ptrs $porta
 	fun_inisocks() {
 		sleep 1
-		screen -dmS proxy python /etc/SSHPlus/proxy.py $porta
-		 [[ $(grep -wc "proxy.py" /etc/autostart) = '0' ]] && {
-		echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'proxy' -X quit;  screen -dmS proxy python /etc/SSHPlus/proxy.py $porta; }" >>/etc/autostart
-	} || {
-	    sed -i '/proxy.py/d' /etc/autostart
-		echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'proxy' -X quit;  screen -dmS proxy python /etc/SSHPlus/proxy.py $porta; }" >>/etc/autostart
+		screen -dmS proxy1 antcrashvpn.sh "$porta"
+		[[ $(grep -wc "antcrashvpn.sh" /etc/autostart) = '0' ]] && {
+			echo -e "netstat -tlpn | grep -w $porta > /dev/null || screen -dmS proxy1 antcrashvpn.sh $porta" >>/etc/autostart
+		} || {
+			sed -i '/antcrashvpn.sh/d' /etc/autostart
+			echo -e "netstat -tlpn | grep -w $porta > /dev/null || screen -dmS proxy1 antcrashvpn.sh $porta" >>/etc/autostart
 		}
 	}
 		echo ""
@@ -1448,85 +1449,87 @@ exit 0' >$RCLOCAL
 		echo -e "\033[1;32mSOCKS ATIVADO COM SUCESSO\033[1;33m"
 		sleep 3
 		menu_proxy
-	}
-	fun_websocket() {
-	if ps x | grep -w wsproxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
-				clear
-				echo -e "\E[41;1;37m             WEBSOCKET              \E[0m"
-				echo ""
-				fun_wssocksoff() {
-					for pidproxy in $(screen -ls | grep ".ws" | awk {'print $1'}); do
-						screen -r -S "$pidproxy" -X quit
-					done
-					[[ $(grep -wc "wsproxy.py" /etc/autostart) != '0' ]] && {
-						sed -i '/wsproxy.py/d' /etc/autostart
-					}
-					sleep 1
-					screen -wipe >/dev/null
-				}
-				echo -e "\033[1;32mDESATIVANDO O WEBSOCKET\033[1;33m"
-				echo ""
-				fun_bar 'fun_wssocksoff'
-				echo ""
-				echo -e "\033[1;32mWEBSOCKET DESATIVADO COM SUCESSO!\033[1;33m"
-				sleep 3
-				menu_proxy
-			else
-				clear
-				echo -e "\E[44;1;37m             WEBSOCKET              \E[0m"
-				echo ""
-				echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR \033[1;33m?\033[1;37m: "
-				read porta
-				[[ -z "$porta" ]] && {
-					echo ""
-					echo -e "\033[1;31mPorta invalida!"
-					sleep 3
-					clear
-					menu_proxy
-				}
-				verif_ptrs $porta
-				fun_iniwssocks() {
-					sleep 1
-					screen -dmS ws python /etc/SSHPlus/wsproxy.py $porta
-					[[ $(grep -wc "wsproxy.py" /etc/autostart) = '0' ]] && {
-						echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'ws' -X quit;  screen -dmS ws python /etc/SSHPlus/wsproxy.py $porta; }" >>/etc/autostart
-					} || {
-						sed -i '/wsproxy.py/d' /etc/autostart
-						echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'ws' -X quit;  screen -dmS ws python /etc/SSHPlus/wsproxy.py $porta; }" >>/etc/autostart
-					}
-				}
-				echo ""
-				echo -e "\033[1;32mINICIANDO O WEBSOCKET\033[1;33m"
-				echo ""
-				fun_bar 'fun_iniwssocks'
-				echo ""
-				echo -e "\033[1;32WSSOCKS ATIVADO COM SUCESSO\033[1;33m"
-				sleep 3
-				menu_proxy
-	}
-	fun_security() {
-	if ps x | grep -w websecurity | grep -v grep 1>/dev/null 2>/dev/null; then
-		echo -e "\E[41;1;37m          WEBSOCKET SECURITY         \E[0m"
+	fi
+}
+fun_websocket() {
+        clear
+	if ps x | grep -w antcrashvpn2.sh | grep -v grep 1>/dev/null 2>/dev/null; then
+		echo -e "\E[41;1;37m             WEBSOCKET              \E[0m"
 		echo ""
-		fun_securityoff() {
-			for pidsecurity in $(screen -ls | grep ".websecurity" | awk {'print $1'}); do
-				screen -r -S "$pidsecurity" -X quit
-			done
-			[[ $(grep -wc "websecurity" /etc/autostart) != '0' ]] && {
-				sed -i '/websecurity/d' /etc/autostart
-			}
-			sleep 1
-			screen -wipe >/dev/null
+	fun_wssocksoff() {
+		for pidwebsocket in $(screen -ls | grep ".proxy2" | awk {'print $1'}); do
+			screen -r -S "$pidwebsocket" -X quit
+		done
+		[[ $(grep -wc "antcrashvpn2.sh" /etc/autostart) != '0' ]] && {
+			sed -i '/antcrashvpn2.sh/d' /etc/autostart
 		}
-		echo -e "\033[1;32mDESATIVANDO O WEBSOCKET SECURITY\033[1;33m"
+		sleep 1
+		screen -wipe >/dev/null
+	}
+		echo -e "\033[1;32mDESATIVANDO O WEBSOCKET\033[1;33m"
+		echo ""
+		fun_bar 'fun_wssocksoff'
+		echo ""
+		echo -e "\033[1;32mWEBSOCKET DESATIVADO COM SUCESSO!\033[1;33m"
+		sleep 3
+		menu_proxy
+	else
+		clear
+		echo -e "\E[44;1;37m             WEBSOCKET              \E[0m"
+		echo ""
+		echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR \033[1;33m?\033[1;37m: "
+		read porta
+		[[ -z "$porta" ]] && {
+			echo ""
+			echo -e "\033[1;31mPorta invalida!"
+			sleep 3
+			clear
+			menu_proxy
+		}
+		verif_ptrs $porta
+	fun_iniwssocks() {
+		sleep 1
+		screen -dmS proxy2 antcrashvpn2.sh "$porta"
+		[[ $(grep -wc "antcrashvpn2.sh" /etc/autostart) = '0' ]] && {
+			echo -e "netstat -tlpn | grep -w $porta > /dev/null || screen -dmS proxy2 antcrashvpn2.sh $porta" >>/etc/autostart
+		} || {
+			sed -i '/antcrashvpn2.sh/d' /etc/autostart
+			echo -e "netstat -tlpn | grep -w $porta > /dev/null || screen -dmS proxy2 antcrashvpn2.sh $porta" >>/etc/autostart
+		}
+	}
+		echo ""
+		echo -e "\033[1;32mINICIANDO O WEBSOCKET\033[1;33m"
+		echo ""
+		fun_bar 'fun_iniwssocks'
+		echo ""
+		echo -e "\033[1;32WEBSOCKET ATIVADO COM SUCESSO\033[1;33m"
+		sleep 3
+		menu_proxy
+	fi
+}
+fun_security() {
+        clear
+    if ps x | grep -w antcrashvpn3.sh | grep -v grep 1>/dev/null 2>/dev/null; then
+	    echo -e "\E[41;1;37m          WEBSOCKET SECURITY         \E[0m"
+		echo ""
+	fun_securityoff() {
+	    for pidsecurity in $(screen -ls | grep ".websecurity" | awk {'print $1'}); do
+		    screen -r -S "$pidsecurity" -X quit
+		done
+	    [[ $(grep -wc "antcrashvpn3.sh" /etc/autostart) != '0' ]] && {
+		    sed -i '/antcrashvpn3.sh/d' /etc/autostart
+		}
+		sleep 1
+		screen -wipe >/dev/null
+	}
+	    echo -e "\033[1;32mDESATIVANDO O WEBSOCKET SECURITY\033[1;33m"
 		echo ""
 		fun_bar 'fun_securityoff'
 		echo ""
-		echo -e "\033[1;32mSECURITY DESATIVADO COM SUCESSO!\033[1;33m"
-		
+		echo -e "\033[1;32mSECURITY DESATIVADO COM SUCESSO!\033[1;33m"		
 		menu_proxy
 	else
-		echo -e "\E[44;1;37m          WEBSOCKET SECURITY         \E[0m"
+	    echo -e "\E[44;1;37m          WEBSOCKET SECURITY         \E[0m"
 		echo ""
 		echo -e "\033[1;32mQUAL PORTA DESEJA ULTILIZAR ? \033"
 		echo ""
@@ -1534,21 +1537,18 @@ exit 0' >$RCLOCAL
 		echo ""
 		read -p "$(echo -e "\033[1;32mQUAL PORTA DESEJA UTILIZAR? \033[1;37m: ")" portaws
 		[[ -z "$portaws" ]] && {
-			echo ""
-			echo -e "\033[1;31mPorta invalida!"
-			
-			menu_proxy
+		    echo ""
+		    echo -e "\033[1;31mPorta invalida!"
+		    menu_proxy
 		}
 		verif_ptrs $portaws
-		fun_inisecurity() {
-			sleep 1
-			screen -dmS websecurity /bin/websecurity -proxy_port 0.0.0.0:$portaws -msg=SECURITY
-			[[ $(grep -wc "websecurity" /etc/autostart) = '0' ]] && {
-				echo -e "netstat -tlpn | grep -w $portaws > /dev/null || {  screen -r -S 'websecurity' -X quit;  screen -dmS websecurity /bin/websecurity -proxy_port 0.0.0.0:$portaws -msg=SECURITY; }" >>/etc/autostart
-			} || {
-				sed -i '/security/d' /etc/autostart
-				echo -e "netstat -tlpn | grep -w $portaws > /dev/null || {  screen -r -S 'websecurity' -X quit;  screen -dmS websecurity /bin/websecurity -proxy_port 0.0.0.0:$portaws -msg=SECURITY; }" >>/etc/autostart
-			}
+	fun_inisecurity() {
+	    sleep 1
+		[[ $(grep -wc "antcrashvpn2.sh" /etc/autostart) = '0' ]] && {
+			echo -e "netstat -tlpn | grep -w $portaws > /dev/null || screen -dmS proxy2 antcrashvpn3.sh $portaws -msg=SECURITY" >>/etc/autostart
+		} || {
+			sed -i '/antcrashvpn2.sh/d' /etc/autostart
+			echo -e "netstat -tlpn | grep -w $portaws > /dev/null || screen -dmS proxy2 antcrashvpn3.sh $portaws -msg=SECURITY" >>/etc/autostart
 		}
 		echo ""
 		echo -e "\033[1;32mINICIANDO WEBSOCKET SECURITY\033[1;33m"
@@ -1556,50 +1556,51 @@ exit 0' >$RCLOCAL
 		fun_bar 'fun_inisecurity'
 		echo ""
 		echo -e "\033[1;32SECURITY ATIVADO COM SUCESSO\033[1;33m"
-		
 		menu_proxy
 	}
-	menu_proxy() {
+	fi
+}
+menu_proxy() {
 		clear
 		[[ $(screen -list | grep -wc 'proxy1') != '0' ]] && sks02="\033[1;32m⬤ " || sks02="\033[1;31m⬤ "
 		[[ $(screen -list | grep -wc 'proxy2') != '0' ]] && sks04="\033[1;32m⬤ " || sks04="\033[1;31m⬤ "
-		echo -e "\E[44;1;37m             PROXY            \E[0m"
+		echo -e "\E[44;1;37m          PROXY MANAGER        \E[0m"
 		echo -e "\033[0;36m╔════════════•⊱✦⊰•════════════╗\033[0m"
 		[[ $(netstat -nplt | grep -wc 'proxy') != '0' ]] && {
 			sks13="\033[1;32m⬤ "
 			echo -e "   \033[1;33mPROXY-PRO: \033[1;32m$(netstat -nplt | grep 'proxy' | awk -F ":" {'print $4'} | xargs)"
-		    } || {
+		} || {
 			sks13="\033[1;31m⬤ "
-		    }
+		}
 		[[ "$(netstat -tlpn | grep 'python' | wc -l)" != '0' ]] && {
-				echo -e "   \033[1;33mSOCKS/WEBSOCKET: \033[1;32m$(netstat -nplt | grep 'python' | awk {'print $4'} | cut -d: -f2 | xargs)"
-				sks400="\033[1;32m⬤ "
-			} || {
-				sks400="\033[1;31m⬤ "
-			}
+			echo -e "   \033[1;33mSOCKS/WEBSOCKET: \033[1;32m$(netstat -nplt | grep 'python' | awk {'print $4'} | cut -d: -f2 | xargs)"
+			sks400="\033[1;32m⬤ "
+		} || {
+			sks400="\033[1;31m⬤ "
+		}
 		[[ "$(netstat -tlpn | grep 'squid' | wc -l)" != '0' ]] && {
-				echo -e "   \033[1;33mSQUID: \033[1;32m$(netstat -nplt | grep 'squid' | awk -F ":" {'print $4'} | xargs)"
-				sks03="\033[1;32m⬤ "
-			} || {
-				sks03="\033[1;31m⬤ "
-			}
-			[[ "$(netstat -tlpn | grep 'websecurity' | wc -l)" != '0' ]] && {
-				echo -e "   \033[1;33mSECURITY \033[1;32m$(netstat -nplt | grep 'websecurity' | awk -F ":" {'print $4'} | xargs)"
-				stssec="\033[1;32m⬤ "
-			} || {
-				stssec="\033[1;31m○⬤ "
-			}
+			echo -e "   \033[1;33mSQUID: \033[1;32m$(netstat -nplt | grep 'squid' | awk -F ":" {'print $4'} | xargs)"
+			sks03="\033[1;32m⬤ "
+	    } || {
+			sks03="\033[1;31m⬤ "
+		}
+		[[ "$(netstat -tlpn | grep 'websecurity' | wc -l)" != '0' ]] && {
+			echo -e "   \033[1;33mSECURITY \033[1;32m$(netstat -nplt | grep 'websecurity' | awk -F ":" {'print $4'} | xargs)"
+			stsec="\033[1;32m⬤ "
+		} || {
+			stsec="\033[1;31m⬤ "
+		}
 		echo -e "\033[0;36m° ° ° ° ° ° ° ° ° ° ° ° ° ° ° °\033[0m"
 		echo -e "\033[1;31m[\033[1;36m01\033[1;31m] \033[1;37m• \033[1;37mPROXY-PRO $sks13\033[1;31m
 [\033[1;36m02\033[1;31m] \033[1;37m• \033[1;37mSOCKS $sks02\033[1;31m
 [\033[1;36m03\033[1;31m] \033[1;37m• \033[1;37mSQUID $sks03\033[1;31m
-[\033[1;36m04\033[1;31m] \033[1;37m• \033[1;37mSECURITY $stssec\033[1;31m
+[\033[1;36m04\033[1;31m] \033[1;37m• \033[1;37mSECURITY $stsec\033[1;31m
 [\033[1;36m05\033[1;31m] \033[1;37m• \033[1;37mWEBSOCKET $sks04\033[1;31m
 [\033[1;36m00\033[1;31m] \033[1;37m• \033[1;37mVOLTAR\033[0m"
 		echo -e "\033[0;36m╚════════════•⊱✦⊰•════════════╝\033[0m"
 		echo -ne "  \033[1;31m➤ \033[1;32mOPÇÃO\033[1;33m\033[1;31m\033[1;37m: ";
-        read option
-        case $option in
+    read option
+    case $option in
     1 | 01)
 		clear
 	    bash <(wget -qO- https://raw.githubusercontent.com/vmell0/RustyProxy/refs/heads/main/install.sh)
@@ -1616,9 +1617,9 @@ exit 0' >$RCLOCAL
     ;;
     4 | 04)
         clear
-	[[ ! -e /bin/websecurity ]] && {
-	    wget -qO /bin/websecurity https://raw.githubusercontent.com/root719/TMY-SSH-PLUS-V3/main/websecurity
-		chmod +x /bin/websecurity
+	[[ ! -e /etc/SSHPlus/websecurity ]] && {
+	    wget -qO /etc/SSHPlus/websecurity https://raw.githubusercontent.com/root719/TMY-SSH-PLUS-V3/main/websecurity
+		chmod +x /etc/SSHPlus/websecurity
 	}
         fun_security
     ;;
@@ -1635,29 +1636,8 @@ exit 0' >$RCLOCAL
 	    sleep 2
 		menu_proxy
 	;;
+    esac
 }
-		elif [[ "$resp" = '3' ]]; then
-		    clear
-			echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mCORRIGINDO SSH \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
-            echo ""
-			fun_cossh () {
-	        echo 'MaxStartups 1500:10:1500' >> /etc/ssh/sshd_config && service ssh restart
-	        }
-		    fun_bar 'fun_cossh'
-			sleep 2
-			fun_conexao
-		elif [[ "$resp" = '0' ]]; then
-			clear
-		    echo ""
-		    echo -e "\033[1;33mVOLTANDO...\033[0m"
-		    sleep 1
-			fun_conexao
-		else
-			echo -e "\n\033[1;31mOpcao invalida!"
-			sleep 2
-			fun_conexao
-		fi
-	}
 	x="ok"
 	fun_conexao() {
 		while true $x != "ok"; do
