2.7.5.0

diff --git a/Modulos/conexao b/Modulos/conexao
--- a/Modulos/conexao
+++ b/Modulos/conexao
@@ -57,22 +57,61 @@ executar_comando() {
 			${comando[1]} >/dev/null 2>&1
 			touch $HOME/fim
 		) >/dev/null 2>&1 &
-		tput civis
-		echo -ne "\033[1;33mAGUARDE \033[1;37m- \033[1;33m["
-		while true; do
-			for ((i = 0; i < 18; i++)); do
-				echo -ne "\033[1;31m#"
-				sleep 0.1s
-			done
-			[[ -e $HOME/fim ]] && rm $HOME/fim && break
-			echo -e "\033[1;33m]"
-			sleep 1s
-			tput cuu1
-			tput dl1
-			echo -ne "\033[1;33mAGUARDE \033[1;37m- \033[1;33m["
-		done
-		echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
-		tput cnorm
+		function error {
+  echo "Usage: $0 [SECONDS]"
+  case $1 in
+    1) echo "Pass one argument only"
+    exit 1
+    ;;
+    2) echo "Parameter must be a number"
+    exit 2
+    ;;
+    *) echo "Unknown error"
+    exit 999
+  esac
+}
+
+[[ $# -ne 1 ]] && error 1
+[[ $1 =~ ^[0-9]+$ ]] || error 2
+
+duration=${1}
+barsize=$((`tput cols` - 7))
+unity=$(($barsize / $duration))
+increment=$(($barsize%$duration))
+skip=$(($duration/($duration-$increment)))
+curr_bar=0
+prev_bar=
+for (( elapsed=1; elapsed<=$duration; elapsed++ ))
+do
+  # Elapsed
+prev_bar=$curr_bar
+  let curr_bar+=$unity
+  [[ $increment -eq 0 ]] || {  
+    [[ $skip -eq 1 ]] &&
+      { [[ $(($elapsed%($duration/$increment))) -eq 0 ]] && let curr_bar++; } ||
+    { [[ $(($elapsed%$skip)) -ne 0 ]] && let curr_bar++; }
+  }
+  [[ $elapsed -eq 1 && $increment -eq 1 && $skip -ne 1 ]] && let curr_bar++
+  [[ $(($barsize-$curr_bar)) -eq 1 ]] && let curr_bar++
+  [[ $curr_bar -lt $barsize ]] || curr_bar=$barsize
+  for (( filled=0; filled<=$curr_bar; filled++ )); do
+    printf "▇"
+  done
+
+  # Remaining
+  for (( remain=$curr_bar; remain<$barsize; remain++ )); do
+    printf " "
+  done
+
+  # Percentage
+  printf "| %s%%" $(( ($elapsed*100)/$duration))
+
+  # Return
+  sleep 1
+  printf "\r"
+done
+printf "\n"
+exit 0
 	}
 	verif_ptrs() {
 		porta=$1
@@ -2129,9 +2168,9 @@ case $option in
             menuop
 			;;
 			13)
-   bash <(curl -sL https://raw.githubusercontent.com/vmell0/RustyProxy/refs/heads/main/install.sh)
-		 clear
-	  proxypro
+            fun_bar 'bash <(curl -sL https://raw.githubusercontent.com/vmell0/RustyProxy/refs/heads/main/install.sh)'
+		    clear
+	        proxypro
 			;;
 			0 | 00)
 			clear
