2.0.1

diff --git a/Modulos/menu b/Modulos/menu
--- a/Modulos/menu
+++ b/Modulos/menu
@@ -243,48 +243,31 @@ echo -e "\033[0;36m  \033[1;36mHora: \033[1;37m$_hora    \033[1;31m  \033[1;36mE
     echo -e "\033[1;31m  \033[1;32mOnlines:\033[1;37m $_onlin    \033[1;31m  \033[1;32mExpirados: \033[1;37m$_userexp \033[1;31m  \033[1;32mTotal: \033[1;37m$_tuser\033[0m     \033[1;31m"
     var01='\033[1;37m•'
 } || {
-    echo -e "\033[1;31m         \033[1;33m[\033[1;31m!\033[1;33m]  \033[1;32mEXISTE UMA ATUALIZACAO DISPONIVEL  \033[1;33m[\033[1;31m!\033[1;33m]\033[0m        \033[1;31m"
+    echo -e ""
     var01="\033[1;32m!"
 }
 echo -e "\033[0;36m° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° °\033[0m"
-echo -e "\033[0;31m   [\033[1;36m14\033[0;31m] \033[1;37m• \033[1;37mREINICIAR SISTEMA \033[0;31m 
-\033[0;31m   [\033[1;36m15\033[0;31m] \033[1;37m• \033[1;37mREINICIAR SERVICOS \033[0;31m 
-\033[0;31m   [\033[1;36m16\033[0;31m] \033[1;37m• \033[1;37mMUDAR SENHA ROOT \033[1;31m  
-\033[0;31m   [\033[1;36m17\033[0;31m] \033[1;37m• \033[1;37mAUTO EXECUCAO $autm \033[0;31m 
-\033[0;31m   [\033[1;36m18\033[0;31m] \033[1;37m• \033[1;37mBLOCK TORRENT $stsf \033[0;31m 
-\033[0;31m   [\033[1;36m19\033[0;31m] \033[1;37m• \033[1;37mDESINSTALAR SSH-PRO \033[0;31m
-\033[0;31m   [\033[1;36m20\033[0;31m] \033[1;37m• \033[1;37mBLOQUEADOR DE SITES \033[0;31m
+echo -e "\033[0;31m   [\033[1;36m14\033[0;31m] \033[1;37m• \033[1;37mAUTO EXECUCAO $autm \033[0;31m 
+\033[0;31m   [\033[1;36m15\033[0;31m] \033[1;37m• \033[1;37mBLOCK TORRENT $stsf \033[0;31m 
+\033[0;31m   [\033[1;36m16\033[0;31m] \033[1;37m• \033[1;37mDESINSTALAR SSH-PRO \033[0;31m
+\033[0;31m   [\033[1;36m17\033[0;31m] \033[1;37m• \033[1;37mBLOQUEADOR DE SITES \033[0;31m
 \033[0;31m   [\033[1;36m00\033[0;31m] \033[1;37m• \033[1;37mVOLTAR  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
 echo -e "╚═════════════════════════•⊱✦⊰•═════════════════════════╝" | lolcat
 echo -ne "\033[1;31m➤ \033[1;32mOPÇÃO\033[1;33m\033[1;31m\033[1;37m: "; read x
 case "$x" in
    14)
    clear
-   reiniciarsistema
+   autoexec
    ;;
    15)
    clear
-   reiniciarservicos
-   sleep 3
+   blockt
    ;;
    16)
    clear
-   senharoot
-   sleep 3
-   ;;
-   17)
-   clear
-   autoexec
-   ;;
-   18)
-   clear
-   blockt
-   ;;
-   19)
-   clear
    delscript
    ;;
-   20)
+   17)
    clear
    blocksite
    ;;
@@ -305,7 +288,7 @@ echo -e "\033[0;36m╔═══════════════════�
     echo -e "\033[1;31m  \033[1;32mOnlines:\033[1;37m $_onlin    \033[1;31m  \033[1;32mExpirados: \033[1;37m$_userexp \033[1;31m  \033[1;32mTotal: \033[1;37m$_tuser\033[0m     \033[1;31m"
     var01='\033[1;37m•'
 } || {
-    echo -e "\033[1;31m         \033[1;33m[\033[1;31m!\033[1;33m]  \033[1;32mEXISTE UMA ATUALIZACAO DISPONIVEL  \033[1;33m[\033[1;31m!\033[1;33m]\033[0m        \033[1;31m"
+    echo -e ""
     var01="\033[1;32m!"
 }
 echo -e "\033[0;36m° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° °\033[0m"
@@ -370,6 +353,67 @@ case "$x" in
    ;;
 esac
 }
+menu4 (){
+clear
+echo -e "\E[44;1;37m              🚀 GERENCIAR SERVIDOR 🚀               \E[0m"
+echo -e "\033[0;36m╔═══════════════════════•⊱✦⊰•═══════════════════════╗\033[0m"
+[[ ! -e /tmp/att ]]  && {
+echo -e "\033[0;36m  \033[1;32mSISTEMA           \033[1;31m  \033[1;32mMEMÓRIA RAM      \033[1;31m \033[1;32m PROCESSADOR      \033[1;31m"
+echo -e "\033[0;36m  \033[1;36mOS: \033[1;37m$_system    \033[1;31m  \033[1;36mTotal:\033[1;37m$_ram \033[1;31m  \033[1;36mNucleos: \033[1;37m$_core\033[0m   \033[1;31m"
+echo -e "\033[0;36m  \033[1;36mHora: \033[1;37m$_hora    \033[1;31m  \033[1;36mEm uso: \033[1;37m$_usor \033[1;31m  \033[1;36mEm uso: \033[1;37m$_usop\033[0m    \033[1;31m"
+    var01='\033[1;37m•'
+} || {
+    echo -e ""
+    var01="\033[1;32m!"
+}
+echo -e "\033[0;36m° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° °\033[0m"
+echo -e "\033[0;31m   [\033[1;36m01\033[0;31m] \033[1;37m• \033[1;37mSPEEDTEST \033[0;31m  
+\033[0;31m   [\033[1;36m02\033[0;31m] \033[1;37m• \033[1;37mTRAFEGO \033[0;31m 
+\033[0;31m   [\033[1;36m03\033[0;31m] \033[1;37m• \033[1;37mREINICIAR SISTEMA \033[0;31m 
+\033[0;31m   [\033[1;36m04\033[0;31m] \033[1;37m• \033[1;37mREINICIAR SERVIÇOS \033[1;31m  
+\033[0;31m   [\033[1;36m05\033[0;31m] \033[1;37m• \033[1;37mMUDAR SENHA ROOT \033[0;31m 
+\033[0;31m   [\033[1;36m00\033[0;31m] \033[1;37m• \033[1;37mVOLTAR  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
+echo -e "\033[0;36m╚═══════════════════════•⊱✦⊰•═══════════════════════╝\033[0m"
+echo -ne "\033[1;31m➤ \033[1;32mOPÇÃO\033[1;33m\033[1;31m\033[1;37m: "; read x
+case "$x" in
+   1 | 01)
+   clear
+   velocity
+   echo -ne "\n\033[1;31m   ENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
+   clear
+   ;;
+   2 | 02)
+   clear
+   trafegototal
+   echo -ne "\n\033[1;31m   ENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
+   clear
+   ;;
+   3 | 03)
+   clear
+   reiniciarsistema
+   ;;
+   4 | 04)
+   clear
+   reiniciarservicos
+   sleep 3
+   ;;
+   5 | 05)
+   clear
+   senharoot
+   sleep 3
+   ;;
+   ;;
+   0 | 00)
+   clear
+   menu
+   ;;
+   *)
+   echo -e "\n\033[1;31mOpcao invalida !\033[0m"
+   sleep 2
+   menu3
+   ;;
+esac
+}
 while true $x != "ok"
 do
 stsl=$(ps x | grep "limiter"|grep -v grep > /dev/null && echo -e "\033[1;32m[ON] " || echo -e "\033[1;31m[OFF] ")
@@ -413,7 +457,7 @@ echo -e "\033[0;36m  \033[1;36mOS: \033[1;37m$_system    \033[1;31m  \033[1;36mT
 echo -e "\033[0;36m  \033[1;36mHora: \033[1;37m$_hora    \033[1;31m  \033[1;36mEm uso: \033[1;37m$_usor \033[1;31m  \033[1;36mEm uso: \033[1;37m$_usop\033[0m    \033[1;31m"
 echo -e "\033[0;36m  \033[1;32mOnlines:\033[1;37m $_onlin    \033[1;31m  \033[1;32mExpirados: \033[1;37m$_userexp \033[1;31m  \033[1;32mTotal: \033[1;37m$_tuser     \033[1;31m"
 echo -e "\033[0;36m° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° °\033[0m"
-echo -e "\033[0;36m   \033[0;31m[\033[1;36m01\033[0;31m] \033[1;37m• \033[1;37mUSUARIO \033[0;31m                  [\033[1;36m08\033[0;31m] \033[1;37m• \033[1;37mSPEEDTEST  \033[1;31m      
+echo -e "\033[0;36m   \033[0;31m[\033[1;36m01\033[0;31m] \033[1;37m• \033[1;37mUSUARIO \033[0;31m                  [\033[1;36m08\033[0;31m] \033[1;37m• \033[1;37mSERVIDOR  \033[1;31m      
 \033[0;31m   [\033[1;36m02\033[0;31m] \033[1;37m• \033[1;37mOTIMIZAR \033[0;31m                 [\033[1;36m09\033[0;31m] \033[1;37m• \033[1;37mBADVPN  \033[1;31m          
 \033[0;31m   [\033[1;36m03\033[0;31m] \033[1;37m• \033[1;37mATUALIZAR \033[0;31m                [\033[1;36m10\033[0;31m] \033[1;37m• \033[1;37mBACKUP \033[1;31m        
 \033[0;31m   [\033[1;36m04\033[0;31m] \033[1;37m• \033[1;37mFIREWALL \033[0;31m                 [\033[1;36m11\033[0;31m] \033[1;37m• \033[1;37mLIMITER $stsl  \033[1;31m       
@@ -456,10 +500,7 @@ case "$x" in
    conexao
    ;;
    8 | 08)
-   clear
-   velocity
-   echo -ne "\n\033[1;31m   ENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
-   clear
+   menu4
    ;;
    9 | 09)
    clear
