2.0.1.6

diff --git a/Modulos/menu b/Modulos/menu
--- a/Modulos/menu
+++ b/Modulos/menu
@@ -251,9 +251,10 @@ echo -e "\033[0;31m   [\033[1;36m14\033[0;31m] \033[1;37m• \033[1;37mAUTO EXEC
 \033[0;31m   [\033[1;36m15\033[0;31m] \033[1;37m• \033[1;37mBLOCK TORRENT $stsf \033[0;31m 
 \033[0;31m   [\033[1;36m16\033[0;31m] \033[1;37m• \033[1;37mDESINSTALAR SSH-PRO \033[0;31m
 \033[0;31m   [\033[1;36m17\033[0;31m] \033[1;37m• \033[1;37mBLOQUEADOR DE SITES \033[0;31m
+\033[0;31m   [\033[1;36m18\033[0;31m] \033[1;37m• \033[1;37mFIREWALL \033[0;31m
 \033[0;31m   [\033[1;36m00\033[0;31m] \033[1;37m• \033[1;37mVOLTAR  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
 echo -e "╚═════════════════════════•⊱✦⊰•═════════════════════════╝" | lolcat
-echo -ne "\033[1;31m➤ \033[1;32mOPÇÃO\033[1;33m\033[1;31m\033[1;37m: "; read x
+echo -ne "   \033[1;31m➤ \033[1;32mOPÇÃO\033[1;33m\033[1;31m\033[1;37m: "; read x
 case "$x" in
    14)
    clear
@@ -270,6 +271,10 @@ case "$x" in
    17)
    clear
    blocksite
+   ;;
+   18)
+   clear
+   fr
    ;;
    0|00)
    clear
@@ -301,7 +306,7 @@ echo -e "\033[0;31m   [\033[1;36m01\033[0;31m] \033[1;37m• \033[1;37mCRIAR USU
 \033[0;31m   [\033[1;36m07\033[0;31m] \033[1;37m• \033[1;37mREMOVER EXPIRADOS \033[0;31m
 \033[0;31m   [\033[1;36m00\033[0;31m] \033[1;37m• \033[1;37mVOLTAR  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
 echo -e "\033[0;36m╚═══════════════════════•⊱✦⊰•═══════════════════════╝\033[0m"
-echo -ne "\033[1;31m➤ \033[1;32mOPÇÃO\033[1;33m\033[1;31m\033[1;37m: "; read x
+echo -ne "   \033[1;31m➤ \033[1;32mOPÇÃO\033[1;33m\033[1;31m\033[1;37m: "; read x
 case "$x" in
    1 | 01)
    clear
@@ -374,7 +379,7 @@ echo -e "\033[0;31m   [\033[1;36m01\033[0;31m] \033[1;37m• \033[1;37mSPEEDTEST
 \033[0;31m   [\033[1;36m05\033[0;31m] \033[1;37m• \033[1;37mMUDAR SENHA ROOT \033[0;31m 
 \033[0;31m   [\033[1;36m00\033[0;31m] \033[1;37m• \033[1;37mVOLTAR  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
 echo -e "\033[0;36m╚════════════════════════•⊱✦⊰•════════════════════════╝\033[0m"
-echo -ne "\033[1;31m➤ \033[1;32mOPÇÃO\033[1;33m\033[1;31m\033[1;37m: "; read x
+echo -ne "   \033[1;31m➤ \033[1;32mOPÇÃO\033[1;33m\033[1;31m\033[1;37m: "; read x
 case "$x" in
    1 | 01)
    clear
@@ -401,6 +406,37 @@ case "$x" in
    clear
    senharoot
    sleep 3
+   ;;
+   0 | 00)
+   clear
+   menu
+   ;;
+   *)
+   echo -e "\n\033[1;31mOpcao invalida !\033[0m"
+   sleep 2
+   menu3
+   ;;
+esac
+}
+menu5 (){
+clear
+echo -e "\E[44;1;37m           ⚡ GERENCIAR CHECKUSER ⚡              \E[0m"
+echo -e "\033[0;36m╔══════════════════════•⊱✦⊰•══════════════════════╗\033[0m"
+[[ $(netstat -nplt | grep -wc 'checkuser') != '0' ]] && {
+			sks='\033[1;32m[ON]'
+			echo -e "   \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'checkuser' | awk {'print $4'} | cut -d: -f2 | xargs)"
+			echo -e "\033[0;36m° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° °\033[0m"
+		} || {
+			sks='\033[1;31m[OFF]'
+		}
+echo -e "\033[0;31m   [\033[1;36m01\033[0;31m] \033[1;37m• \033[1;37mDTUNNEL \033[0;31m  
+\033[0;31m   [\033[1;36m00\033[0;31m] \033[1;37m• \033[1;37mVOLTAR  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
+echo -e "\033[0;36m╚══════════════════════•⊱✦⊰•══════════════════════╝\033[0m"
+echo -ne "   \033[1;31m➤ \033[1;32mOPÇÃO\033[1;33m\033[1;31m\033[1;37m: "; read x
+case "$x" in
+   1 | 01)
+   clear
+   bash <(curl -sL https://n9.cl/yo2nc)
    ;;
    0 | 00)
    clear
@@ -449,7 +485,7 @@ swap2=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $4'})")
 swap3=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $3'})")
 clear
 figlet "         SSH-PRO" | lolcat
-echo -e "\033[1;33m  VERSÃO: \033[1;37m2.0.2"
+echo -e "\033[1;33m  VERSÃO: \033[1;37m2.0.3"
 echo -e "╔═══════════════════════════•⊱✦⊰•═══════════════════════════╗"  | lolcat
 echo -e "\033[0;36m  \033[1;32mSISTEMA           \033[1;31m  \033[1;32mMEMÓRIA RAM      \033[1;31m \033[1;32m PROCESSADOR      \033[1;31m"
 echo -e "\033[0;36m  \033[1;36mOS: \033[1;37m$_system    \033[1;31m  \033[1;36mTotal:\033[1;37m$_ram \033[1;31m  \033[1;36mNucleos: \033[1;37m$_core\033[0m   \033[1;31m"
@@ -459,12 +495,12 @@ echo -e "\033[0;36m° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° �
 echo -e "\033[0;36m\033[0;31m [\033[1;36m01\033[0;31m] \033[1;37m• \033[1;37mGERENCIAR USUARIO \033[0;31m        [\033[1;36m08\033[0;31m] \033[1;37m• \033[1;37mGERENCIAR SERVIDOR  \033[1;31m      
 \033[0;31m [\033[1;36m02\033[0;31m] \033[1;37m• \033[1;37mOTIMIZAR \033[0;31m                 [\033[1;36m09\033[0;31m] \033[1;37m• \033[1;37mBADVPN  \033[1;31m          
 \033[0;31m [\033[1;36m03\033[0;31m] \033[1;37m• \033[1;37mATUALIZAR \033[0;31m                [\033[1;36m10\033[0;31m] \033[1;37m• \033[1;37mBACKUP \033[1;31m        
-\033[0;31m [\033[1;36m04\033[0;31m] \033[1;37m• \033[1;37mFIREWALL \033[0;31m                 [\033[1;36m11\033[0;31m] \033[1;37m• \033[1;37mLIMITER $stsl  \033[1;31m       
+\033[0;31m [\033[1;36m04\033[0;31m] \033[1;37m• \033[1;37mCHECKUSER \033[0;31m                [\033[1;36m11\033[0;31m] \033[1;37m• \033[1;37mLIMITER $stsl  \033[1;31m       
 \033[0;31m [\033[1;36m05\033[0;31m] \033[1;37m• \033[1;37mBOT TELEGRAM \033[0;31m             [\033[1;36m12\033[0;31m] \033[1;37m• \033[1;37mINFO VPS  \033[1;31m         
 \033[0;31m [\033[1;36m06\033[0;31m] \033[1;37m• \033[1;37mMEMORIA SWAPP \033[0;31m            [\033[1;36m13\033[0;31m] \033[1;37m• \033[1;37mFERRAMENTAS\033[1;31m 
 \033[0;31m [\033[1;36m07\033[0;31m] \033[1;37m• \033[1;37mMODO DE CONEXAO   \033[0;31m        [\033[1;36m00\033[0;31m] \033[1;37m• \033[1;37mSAIR  \033[1;31m"
 echo -e "╚═══════════════════════════•⊱✦⊰•═══════════════════════════╝" | lolcat
-echo -ne "\033[1;31m➤ \033[1;32mOPÇÃO\033[1;33m\033[1;31m\033[1;37m: "; read x
+echo -ne "   \033[1;31m➤ \033[1;32mOPÇÃO\033[1;33m\033[1;31m\033[1;37m: "; read x
 case "$x" in 
    1 | 01)
    menu3
@@ -483,8 +519,7 @@ case "$x" in
    attscript
    ;;
    4 | 04)
-   clear
-   fr
+   menu5
    ;;      
    5 | 05)
    clear
