1.0.0.67

diff --git a/Modulos/menu b/Modulos/menu
--- a/Modulos/menu
+++ b/Modulos/menu
@@ -246,55 +246,45 @@ echo -e "\033[0;36m  \033[1;36mHora: \033[1;37m$_hora    \033[1;31m  \033[1;36mE
     echo -e "\033[1;31m         \033[1;33m[\033[1;31m!\033[1;33m]  \033[1;32mEXISTE UMA ATUALIZACAO DISPONIVEL  \033[1;33m[\033[1;31m!\033[1;33m]\033[0m        \033[1;31m"
     var01="\033[1;32m!"
 }
-echo -e "\033[0;36m° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° °\033[0m"
-echo -e "\033[0;31m   [\033[1;36m18\033[0;31m] \033[1;37m• \033[1;37mFIREWALL \033[0;31m  
-\033[0;31m   [\033[1;36m19\033[0;31m] \033[1;37m• \033[1;37mREINICIAR SISTEMA \033[0;31m 
-\033[0;31m   [\033[1;36m20\033[0;31m] \033[1;37m• \033[1;37mREINICIAR SERVICOS \033[0;31m 
-\033[0;31m   [\033[1;36m21\033[0;31m] \033[1;37m• \033[1;37mMUDAR SENHA ROOT \033[1;31m  
-\033[0;31m   [\033[1;36m22\033[0;31m] \033[1;37m• \033[1;37mAUTO EXECUCAO $autm \033[0;31m 
-\033[0;31m   [\033[1;36m23\033[0;31m] \033[1;37m• \033[1;37mBLOCK TORRENT $stsf \033[0;31m 
-\033[0;31m   [\033[1;36m24\033[0;31m] \033[1;37m• \033[1;37mBOT TELEGRAM $stsbot \033[0;31m
-\033[0;31m   [\033[1;36m25\033[0;31m] \033[1;37m• \033[1;37mDESINSTALAR SSH-PRO ⚠️ \033[0;31m
-\033[0;31m   [\033[1;36m26\033[0;31m] \033[1;37m• \033[1;37mMAIS FERRAMENTAS ⚒️ \033[0;31m
+echo -e "\033[0;36m° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° °\033[0m"
+echo -e "\033[0;31m   [\033[1;36m14\033[0;31m] \033[1;37m• \033[1;37mREINICIAR SISTEMA \033[0;31m 
+\033[0;31m   [\033[1;36m15\033[0;31m] \033[1;37m• \033[1;37mREINICIAR SERVICOS \033[0;31m 
+\033[0;31m   [\033[1;36m16\033[0;31m] \033[1;37m• \033[1;37mMUDAR SENHA ROOT \033[1;31m  
+\033[0;31m   [\033[1;36m17\033[0;31m] \033[1;37m• \033[1;37mAUTO EXECUCAO $autm \033[0;31m 
+\033[0;31m   [\033[1;36m18\033[0;31m] \033[1;37m• \033[1;37mBLOCK TORRENT $stsf \033[0;31m 
+\033[0;31m   [\033[1;36m19\033[0;31m] \033[1;37m• \033[1;37mDESINSTALAR SSH-PRO ⚠️ \033[0;31m
+\033[0;31m   [\033[1;36m20\033[0;31m] \033[1;37m• \033[1;37mMAIS FERRAMENTAS ⚒️ \033[0;31m
 \033[0;31m   [\033[1;36m00\033[0;31m] \033[1;37m• \033[1;37mVOLTAR  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
 echo -e "╚═════════════════════════•⊱✦⊰•═════════════════════════╝" | lolcat
-echo -ne "\033[1;31m➤ \033[1;32mDIGITE A OPÇÃO\033[1;33m\033[1;31m\033[1;37m: "; read x
+echo -ne "\033[1;31m➤ \033[1;32mOPÇÃO\033[1;33m\033[1;31m\033[1;37m: "; read x
 case "$x" in
-   18)
-   clear
-   fr
-   ;;
-   19)
+   14)
    clear
    reiniciarsistema
    ;;
-   20)
+   15)
    clear
    reiniciarservicos
    sleep 3
    ;;
-   21)
+   16)
    clear
    senharoot
    sleep 3
    ;;
-   22)
+   17)
    clear
    autoexec
    ;;
-   23)
+   18)
    clear
    blockt
    ;;
-   24)
-   clear
-   botssh
-   ;;
-   25)
+   19)
    clear
    delscript
    ;;
-   26)
+   20)
    clear
    utili
    ;;
@@ -307,64 +297,29 @@ case "$x" in
    sleep 2
 esac
 }
-while true $x != "ok"
-do
-stsl=$(ps x | grep "limiter"|grep -v grep > /dev/null && echo -e "\033[1;32m✅ " || echo -e "\033[1;31m❌ ")
-swpp=$(ps x | grep "swap"|grep -v grep > /dev/null && echo -e "\033[1;32m✅ " || echo -e "\033[1;31m❌) ")
-stson=$(ps x | grep "onlineapp"|grep -v grep > /dev/null && echo -e "\033[1;32m✅ " || echo -e "\033[1;31m❌ ")
-stsu=$(ps x | grep "udpvpn"|grep -v grep > /dev/null && echo -e "\033[1;32m✅ " || echo -e "\033[1;31m❌ ")
-if [[ "$(grep -c "Ubuntu" /etc/issue.net)" = "1" ]]; then
-system=$(cut -d' ' -f1 /etc/issue.net)
-system+=$(echo ' ')
-system+=$(cut -d' ' -f2 /etc/issue.net |awk -F "." '{print $1}')
-elif [[ "$(grep -c "Debian" /etc/issue.net)" = "1" ]]; then
-system=$(cut -d' ' -f1 /etc/issue.net)
-system+=$(echo ' ')
-system+=$(cut -d' ' -f3 /etc/issue.net)
-else
-system=$(cut -d' ' -f1 /etc/issue.net)
-fi
-_ons=$(ps -x | grep sshd | grep -v root | grep priv | wc -l)
-[[ "$(cat /etc/SSHPlus/Exp)" != "" ]] && _expuser=$(cat /etc/SSHPlus/Exp) || _expuser="0"
-[[ -e /etc/openvpn/openvpn-status.log ]] && _onop=$(grep -c "10.8.0" /etc/openvpn/openvpn-status.log) || _onop="0"
-[[ -e /etc/default/dropbear ]] && _drp=$(ps aux | grep dropbear | grep -v grep | wc -l) _ondrp=$(($_drp - 1)) || _ondrp="0"
-_onli=$(($_ons + $_onop + $_ondrp))
-_ram=$(printf ' %-9s' "$(free -h | grep -i mem | awk {'print $2'})")
-_usor=$(printf '%-8s' "$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')")
-_usop=$(printf '%-5s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")
-_core=$(printf '%-5s' "$(grep -c cpu[0-9] /proc/stat)")
-_system=$(printf '%-10s' "$system")
-_hora=$(printf '%(%H:%M:%S)T')
-_onlin=$(printf '%-5s' "$_onli")
-_userexp=$(printf '%-5s' "$_expuser")
-_tuser=$(printf '%-5s' "$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)")
-swap1=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $2'})")
-swap2=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $4'})")
-swap3=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $3'})")
+menu3 (){
 clear
-figlet "         SSH-PRO" | lolcat
-echo -e "\033[1;33m  VERSÃO: \033[1;37m1.0.6.0"
-echo -e "╔═══════════════════════════•⊱✦⊰•═══════════════════════════╗"  | lolcat
-echo -e "\033[0;36m  \033[1;32mSISTEMA           \033[1;31m  \033[1;32mMEMÓRIA RAM      \033[1;31m \033[1;32m PROCESSADOR      \033[1;31m"
-echo -e "\033[0;36m  \033[1;36mOS: \033[1;37m$_system    \033[1;31m  \033[1;36mTotal:\033[1;37m$_ram \033[1;31m  \033[1;36mNucleos: \033[1;37m$_core\033[0m   \033[1;31m"
-echo -e "\033[0;36m  \033[1;36mHora: \033[1;37m$_hora    \033[1;31m  \033[1;36mEm uso: \033[1;37m$_usor \033[1;31m  \033[1;36mEm uso: \033[1;37m$_usop\033[0m    \033[1;31m"
-echo -e "\033[0;36m  \033[1;32mOnlines:\033[1;37m $_onlin    \033[1;31m  \033[1;32mExpirados: \033[1;37m$_userexp \033[1;31m  \033[1;32mTotal: \033[1;37m$_tuser     \033[1;31m"
-echo -e "\033[0;36m° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° °\033[0m"
-echo -e "\033[0;36m   \033[0;31m[\033[1;36m01\033[0;31m] \033[1;37m• \033[1;37mCRIAR USUARIO \033[0;31m            [\033[1;36m10\033[0;31m] \033[1;37m• \033[1;37mSPEEDTEST  \033[1;31m      
-\033[0;31m   [\033[1;36m02\033[0;31m] \033[1;37m• \033[1;37mCRIAR TESTE         \033[0;31m      [\033[1;36m11\033[0;31m] \033[1;37m• \033[1;37mTRAFEGO  \033[1;31m          
-\033[0;31m   [\033[1;36m03\033[0;31m] \033[1;37m• \033[1;37mREMOVER USUARIO \033[0;31m          [\033[1;36m12\033[0;31m] \033[1;37m• \033[1;37mOTIMIZAR  \033[1;31m        
-\033[0;31m   [\033[1;36m04\033[0;31m] \033[1;37m• \033[1;37mMONITOR ONLINE \033[0;31m           [\033[1;36m13\033[0;31m] \033[1;37m• \033[1;37mBACKUP  \033[1;31m       
-\033[0;31m   [\033[1;36m05\033[0;31m] \033[1;37m• \033[1;37mMUDAR DATA \033[0;31m               [\033[1;36m14\033[0;31m] \033[1;37m• \033[1;37mBANNER  \033[1;31m         
-\033[0;31m   [\033[1;36m06\033[0;31m] \033[1;37m• \033[1;37mALTERAR LIMITE \033[0;31m           [\033[1;36m15\033[0;31m] \033[1;37m• \033[1;37mLIMITER $stsl\033[1;31m 
-\033[0;31m   [\033[1;36m07\033[0;31m] \033[1;37m• \033[1;37mREMOVER EXPIRADOS \033[0;31m        [\033[1;36m16\033[0;31m] \033[1;37m• \033[1;37mINFO VPS  \033[1;31m  
-\033[0;31m   [\033[1;36m08\033[0;31m] \033[1;37m• \033[1;37mMEMORIA SWAPP \033[0;31m            [\033[1;36m17\033[0;31m] \033[1;37m• \033[1;37mFERRAMENTAS \033[1;31m 
-\033[0;31m   [\033[1;36m09\033[0;31m] \033[1;37m• \033[1;37mMODO DE CONEXAO \033[0;31m          [\033[1;36m00\033[0;31m] \033[1;37m• \033[1;37mSAIR \033[1;31m"
-echo -e "╚═══════════════════════════•⊱✦⊰•═══════════════════════════╝" | lolcat
-echo -e " ╭─────────────────╮ ╭─────────────────╮ ╭─────────────────╮" | lolcat
-echo -e "\033[1;33m   A \033[1;36m➤ \033[1;37m ATUALIZAR \033[0;31m      \033[1;33mB \033[1;36m➤ \033[1;37m BADVPN \033[0;31m      \033[1;33m  P \033[1;36m➤ \033[1;37mPROXY-PRO \033[0m"
-echo -e " ╰─────────────────╯ ╰─────────────────╯ ╰─────────────────╯" | lolcat
-echo -ne "\033[1;31m➤ \033[1;32mDIGITE A OPÇÃO\033[1;33m\033[1;31m\033[1;37m: "; read x
-case "$x" in 
+echo -e "\E[44;1;37m             🚀 GERENCIAR USUARIOS 🚀              \E[0m"
+echo -e "\033[0;36m╔══════════════════════•⊱✦⊰•══════════════════════╗\033[0m"
+[[ ! -e /tmp/att ]]  && {
+    echo -e "\033[1;31m  \033[1;32mOnlines:\033[1;37m $_onlin    \033[1;31m  \033[1;32mExpirados: \033[1;37m$_userexp \033[1;31m  \033[1;32mTotal: \033[1;37m$_tuser\033[0m     \033[1;31m"
+    var01='\033[1;37m•'
+} || {
+    echo -e "\033[1;31m         \033[1;33m[\033[1;31m!\033[1;33m]  \033[1;32mEXISTE UMA ATUALIZACAO DISPONIVEL  \033[1;33m[\033[1;31m!\033[1;33m]\033[0m        \033[1;31m"
+    var01="\033[1;32m!"
+}
+echo -e "\033[0;36m° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° °\033[0m"
+echo -e "\033[0;31m   [\033[1;36m01\033[0;31m] \033[1;37m• \033[1;37mCRIAR USUARIO \033[0;31m  
+\033[0;31m   [\033[1;36m02\033[0;31m] \033[1;37m• \033[1;37mCRIAR TESTE \033[0;31m 
+\033[0;31m   [\033[1;36m03\033[0;31m] \033[1;37m• \033[1;37mREMOVER USUARIO \033[0;31m 
+\033[0;31m   [\033[1;36m04\033[0;31m] \033[1;37m• \033[1;37mUSUARIOS ONLINE \033[1;31m  
+\033[0;31m   [\033[1;36m05\033[0;31m] \033[1;37m• \033[1;37mMUDAR DATA \033[0;31m 
+\033[0;31m   [\033[1;36m06\033[0;31m] \033[1;37m• \033[1;37mALTERAR LIMITE \033[0;31m 
+\033[0;31m   [\033[1;36m07\033[0;31m] \033[1;37m• \033[1;37mREMOVER EXPIRADOS \033[0;31m
+\033[0;31m   [\033[1;36m00\033[0;31m] \033[1;37m• \033[1;37mVOLTAR  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
+echo -e "\033[0;36m╚══════════════════════•⊱✦⊰•══════════════════════╝\033[0m"
+echo -ne "\033[1;31m➤ \033[1;32mOPÇÃO\033[1;33m\033[1;31m\033[1;37m: "; read x
+case "$x" in
    1 | 01)
    clear
    criarusuario
@@ -404,80 +359,137 @@ case "$x" in
    echo ""
    sleep 3
    ;;
-   8 | 08)
+   0 | 00)
    clear
-   swapmemory
-   ;;   
-   9 | 09)
-   clear
-   conexao
-   exit;
+   echo -e "\033[1;33m VOLTANDO...\033[0m"
+   sleep 1s
+   menu
    ;;
-   10)
-   clear
-   velocity
-   echo -ne "\n\033[1;31m   ENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
-   clear
+   *)
+   echo -e "\n\033[1;31mOpcao invalida !\033[0m"
+   sleep 2
+   menu3
    ;;
-   11)
-   clear
-   echo -e "\033[1;32mPARA SAIR CLICK CTRL + C\033[1;36m"
-   sleep 4
-   nload
+esac
+}
+while true $x != "ok"
+do
+stsl=$(ps x | grep "limiter"|grep -v grep > /dev/null && echo -e "\033[1;32m[ON] " || echo -e "\033[1;31m[OFF] ")
+swpp=$(ps x | grep "swap"|grep -v grep > /dev/null && echo -e "\033[1;32m[ON] " || echo -e "\033[1;31m[OFF] ")
+stson=$(ps x | grep "onlineapp"|grep -v grep > /dev/null && echo -e "\033[1;32m[ON] " || echo -e "\033[1;31m[OFF] ")
+stsu=$(ps x | grep "udpvpn"|grep -v grep > /dev/null && echo -e "\033[1;32m[ON] " || echo -e "\033[1;31m[OFF] ")
+if [[ "$(grep -c "Ubuntu" /etc/issue.net)" = "1" ]]; then
+system=$(cut -d' ' -f1 /etc/issue.net)
+system+=$(echo ' ')
+system+=$(cut -d' ' -f2 /etc/issue.net |awk -F "." '{print $1}')
+elif [[ "$(grep -c "Debian" /etc/issue.net)" = "1" ]]; then
+system=$(cut -d' ' -f1 /etc/issue.net)
+system+=$(echo ' ')
+system+=$(cut -d' ' -f3 /etc/issue.net)
+else
+system=$(cut -d' ' -f1 /etc/issue.net)
+fi
+_ons=$(ps -x | grep sshd | grep -v root | grep priv | wc -l)
+[[ "$(cat /etc/SSHPlus/Exp)" != "" ]] && _expuser=$(cat /etc/SSHPlus/Exp) || _expuser="0"
+[[ -e /etc/openvpn/openvpn-status.log ]] && _onop=$(grep -c "10.8.0" /etc/openvpn/openvpn-status.log) || _onop="0"
+[[ -e /etc/default/dropbear ]] && _drp=$(ps aux | grep dropbear | grep -v grep | wc -l) _ondrp=$(($_drp - 1)) || _ondrp="0"
+_onli=$(($_ons + $_onop + $_ondrp))
+_ram=$(printf ' %-9s' "$(free -h | grep -i mem | awk {'print $2'})")
+_usor=$(printf '%-8s' "$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')")
+_usop=$(printf '%-5s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")
+_core=$(printf '%-5s' "$(grep -c cpu[0-9] /proc/stat)")
+_system=$(printf '%-10s' "$system")
+_hora=$(printf '%(%H:%M:%S)T')
+_onlin=$(printf '%-5s' "$_onli")
+_userexp=$(printf '%-5s' "$_expuser")
+_tuser=$(printf '%-5s' "$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)")
+swap1=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $2'})")
+swap2=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $4'})")
+swap3=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $3'})")
+clear
+figlet "         SSH-PRO" | lolcat
+echo -e "\033[1;33m  VERSÃO: \033[1;37m2.0.0"
+echo -e "╔═══════════════════════════•⊱✦⊰•═══════════════════════════╗"  | lolcat
+echo -e "\033[0;36m  \033[1;32mSISTEMA           \033[1;31m  \033[1;32mMEMÓRIA RAM      \033[1;31m \033[1;32m PROCESSADOR      \033[1;31m"
+echo -e "\033[0;36m  \033[1;36mOS: \033[1;37m$_system    \033[1;31m  \033[1;36mTotal:\033[1;37m$_ram \033[1;31m  \033[1;36mNucleos: \033[1;37m$_core\033[0m   \033[1;31m"
+echo -e "\033[0;36m  \033[1;36mHora: \033[1;37m$_hora    \033[1;31m  \033[1;36mEm uso: \033[1;37m$_usor \033[1;31m  \033[1;36mEm uso: \033[1;37m$_usop\033[0m    \033[1;31m"
+echo -e "\033[0;36m  \033[1;32mOnlines:\033[1;37m $_onlin    \033[1;31m  \033[1;32mExpirados: \033[1;37m$_userexp \033[1;31m  \033[1;32mTotal: \033[1;37m$_tuser     \033[1;31m"
+echo -e "\033[0;36m° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° °\033[0m"
+echo -e "\033[0;36m   \033[0;31m[\033[1;36m01\033[0;31m] \033[1;37m• \033[1;37mGERENCIAR USUARIO \033[0;31m        [\033[1;36m08\033[0;31m] \033[1;37m• \033[1;37mSPEEDTEST  \033[1;31m      
+\033[0;31m   [\033[1;36m02\033[0;31m] \033[1;37m• \033[1;37OTIMIZAR \033[0;31m                  [\033[1;36m09\033[0;31m] \033[1;37m• \033[1;37mBADVPN  \033[1;31m          
+\033[0;31m   [\033[1;36m03\033[0;31m] \033[1;37m• \033[1;37mATUALIZAR \033[0;31m                [\033[1;36m10\033[0;31m] \033[1;37m• \033[1;37mBACKUP \033[1;31m        
+\033[0;31m   [\033[1;36m04\033[0;31m] \033[1;37m• \033[1;37mFIREWALL \033[0;31m                 [\033[1;36m11\033[0;31m] \033[1;37m• \033[1;37mLIMITER $stsl  \033[1;31m       
+\033[0;31m   [\033[1;36m05\033[0;31m] \033[1;37m• \033[1;37mMEMORIA SWAPP\033[0;31m             [\033[1;36m12\033[0;31m] \033[1;37m• \033[1;37mINFO VPS  \033[1;31m         
+\033[0;31m   [\033[1;36m06\033[0;31m] \033[1;37m• \033[1;37mBOT TELEGRAM \033[0;31              [\033[1;36m13\033[0;31m] \033[1;37m• \033[1;37mFERRAMENTAS\033[1;31m 
+\033[0;31m   [\033[1;36m07\033[0;31m] \033[1;37m• \033[1;37mMODO DE CONEXAO   \033[0;31m        [\033[1;36m00\033[0;31m] \033[1;37m• \033[1;37mSAIR  \033[1;31m"
+echo -e "╚═══════════════════════════•⊱✦⊰•═══════════════════════════╝" | lolcat
+echo -ne "\033[1;31m➤ \033[1;32mOPÇÃO\033[1;33m\033[1;31m\033[1;37m: "; read x
+case "$x" in 
+   1 | 01)
+   menu3
    ;;
-   12)
+   2 | 02)
    clear
    otimizar
    echo -ne "\n\033[1;31m   ENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
    clear
    ;;
-   13)
-   userbackup
-   echo -ne "\n\033[1;31m   ENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
-   clear
-   ;;
-   14)
-   clear
-   banner
-   sleep 3
-   ;;
-   15)
-   clear
-   limit_ssh
-   ;;
-   16)
-   clear
-   detalhes
-   echo -ne "\n\033[1;31m   ENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
-   clear
-   ;;
-   17)
-   clear
-   menu2
-   ;;
-   0 | 00)
-   echo -e "\033[1;31m SAINDO DO MENU...\033[0m"
-   sleep 3s
-   exit;
-   clear
-   ;;
-   P | p)
-   clear
-   echo ""
-   fun_bar 'fun_proxypro'
-   clear
-   proxypro
-   ;;
-   B | b)
-   clear
-   menub
-   ;;
-   A | a)
+   3 | 03)
    clear
    echo ""
    fun_bar 'fun_atualizar'
    clear
    attscript
+   ;;
+   4 | 04)
+   clear
+   fr
+   ;;      
+   5 | 05)
+   clear
+   swapmemory
+   ;;
+   6 | 06)
+   clear
+   botssh
+   ;;
+   7 | 07)
+   clear
+   conexao
+   ;;
+   8 | 08)
+   clear
+   velocity
+   echo -ne "\n\033[1;31m   ENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
+   clear
+   ;;
+   9 | 09)
+   clear
+   menub
+   ;;
+   10 | 10)
+   userbackup
+   echo -ne "\n\033[1;31m   ENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
+   clear
+   ;;
+   11 | 11)
+   clear
+   limit_ssh
+   ;;
+   12 | 12)
+   clear
+   detalhes
+   echo -ne "\n\033[1;31m   ENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
+   clear
+   ;;
+   13 | 13)
+   menu2
+   ;;
+   0 | 00)
+   echo -e "\033[1;31m SAINDO DO MENU...\033[0m"
+   sleep 2s
+   clear
+   exit;
    ;;
    *)
    echo -e "\n\033[1;31mOpcao invalida !\033[0m"
